import { index, toFEN, START, fromFEN, applyMove } from './chess.js';
export const REGIONS = [
  { name: 'Lantern Meadow', subtitle: 'Meet your pieces', badge: 'Pathfinder', symbol: '✦', color: '#e8b869', reward: 'The meadow lanterns are glowing. Every piece has a place in your toolkit.', x: 115, y: 270 },
  { name: 'Whispering Woods', subtitle: 'See threats & take care', badge: 'Lookout', symbol: '♧', color: '#91bc91', reward: 'The woodland bridge is open. You are learning to look before you leap.', x: 290, y: 185 },
  { name: 'King’s Sanctuary', subtitle: 'Keep the king safe', badge: 'Guardian', symbol: '♔', color: '#a2c8cf', reward: 'The sanctuary bell is ringing. You know how games end—and how to keep yours alive.', x: 430, y: 300 },
  { name: 'Twin Peaks', subtitle: 'Make a clever plan', badge: 'Tactician', symbol: '◇', color: '#b9a3d8', reward: 'The mountain passage is clear. A little foresight can change the whole board.', x: 590, y: 150 },
  { name: 'River Crossing', subtitle: 'A few special moves', badge: 'Wayfinder', symbol: '≈', color: '#81bcc3', reward: 'The river ferry is ready. You have learned the surprising little rules, too.', x: 745, y: 280 },
  { name: 'The Observatory', subtitle: 'Put it all together', badge: 'Stargazer', symbol: '✺', color: '#e8c887', reward: 'The observatory is awake. The trail ends here, but your chess journey has just begun.', x: 880, y: 170 }
];
function position(pieces, turn = 'w', castle = '', ep = null) {
  const board = Array(64).fill(null);
  for (const [sq, piece] of pieces) board[index(sq)] = { color: piece[0], type: piece[1] };
  return toFEN({ board, turn, castle, ep: ep ? index(ep) : null, half: 0, full: 1 });
}
const P = position;
const lessons = [];
function add(region, title, objective, intro, pieces, goal, hints, success, options = {}) {
  lessons.push({ id: lessons.length, region, title, objective, intro, fen: typeof pieces === 'string' ? pieces : P(pieces), goal, hints, success, mode: 'puzzle', maxMoves: 1, ...options });
}
add(0, 'Meet the rook', 'Light the lantern on a4.', 'Welcome, traveller. Select the ivory rook, then a square. Rooks travel any distance along a row or column. Your first lantern is just up the path.', [['a1','wr']], { type:'reach', squares:['a4'] }, ['The rook follows straight paths. Look above it.', 'Select the rook on a1. The lantern is on a4.', 'Move the rook from a1 to a4.'], 'Straight up! Rooks move along rows and columns, as far as the path is clear.', { mode:'drill', concept:'rook', targets:['a4'] });
add(0, 'A bend in the path', 'Light both lanterns, in order.', 'A rook cannot turn a corner in one move. Light a4 first, then d4. In movement drills you take consecutive moves; there is no opponent taking turns yet.', [['a1','wr']], { type:'route', squares:['a4','d4'] }, ['First go up, then across.', 'Move a1 → a4, then a4 → d4.', 'It takes two straight moves to turn this corner.'], 'Two straight moves made a corner. A chess move always ends before the next direction begins.', { mode:'drill', maxMoves:99, concept:'rook', targets:['a4','d4'] });
add(0, 'Meet the bishop', 'Reach the lantern on f4.', 'Bishops travel diagonally. Notice the colour under your bishop: every square it can reach has that same colour.', [['c1','wb']], { type:'reach', squares:['f4'] }, ['Follow the diagonal up and to the right.', 'The path goes through d2 and e3.', 'Move the bishop from c1 to f4.'], 'A bishop stays on one square colour for the entire game. Its partner starts on the other colour.', { mode:'drill', concept:'bishop', targets:['f4'] });
add(0, 'Meet the knight', 'Hop to the lantern on f4.', 'The knight takes an L-shaped leap: two squares in one direction, then one to the side. It jumps over pieces—even friendly ones.', [['d3','wn'],['d4','wp'],['e3','wp'],['e4','wp']], { type:'reach', squares:['f4'] }, ['The knight can jump over the pawns.', 'From d3, go two columns right and one row up.', 'Move the knight from d3 to f4.'], 'A knight lands on the opposite square colour after each move. The pieces between do not block it.', { mode:'drill', allowed:['n'], concept:'knight', targets:['f4'] });
add(0, 'Meet the queen', 'Reach the lantern on g7.', 'The queen combines rook and bishop movement: rows, columns, and diagonals. Powerful, yes—but it still cannot jump over pieces.', [['d4','wq']], { type:'reach', squares:['g7'] }, ['The lantern is on a diagonal from the queen.', 'Trace d4 → e5 → f6 → g7.', 'Move the queen from d4 to g7.'], 'One clear diagonal. The queen has many options, so take a moment to look around.', { mode:'drill', concept:'queen', targets:['g7'] });
add(0, 'Meet the pawn', 'Advance the pawn to e4.', 'Ivory pawns move toward the top of this board. A pawn moves one square forward, or two on its very first move if both squares are empty. It never moves backwards.', [['e2','wp']], { type:'reach', squares:['e4'] }, ['This pawn is on its starting row, so it has a two-square option.', 'Both e3 and e4 are empty.', 'Move the pawn from e2 to e4.'], 'The first-move double step is optional. After leaving its starting row, a pawn moves just one square forward.', { mode:'drill', concept:'pawn', targets:['e4'] });
add(0, 'A different way to capture', 'Capture the violet pawn on d5.', 'Pawns capture differently from how they move: one square diagonally forward. The violet pawn straight ahead blocks your path; the one diagonally ahead can be captured.', [['e4','wp'],['e5','bp'],['d5','bp']], { type:'capture', square:'d5' }, ['You cannot capture the pawn straight ahead on e5.', 'Look one square forward and left.', 'Move e4 → d5. Your pawn replaces the captured pawn.'], 'You remove an enemy piece by moving onto its square. Pawns do this diagonally, never straight forward.', { mode:'drill', concept:'capture', targets:['d5'] });
add(0, 'Take the scenic route', 'Get the rook to a5.', 'Your own pawn blocks the rook. You cannot jump over it or capture it. Find a clear route around; leave the pawn where it is.', [['a1','wr'],['a3','wp']], { type:'reach', squares:['a5'] }, ['The rook needs a different column.', 'Try a1 → b1 → b5 → a5.', 'Three straight moves can go around the pawn.'], 'A clear path matters. Knights can jump; rooks, bishops, and queens cannot.', { mode:'drill', allowed:['r'], maxMoves:99, concept:'blockers', targets:['a5'] });
add(1, 'Who’s in danger?', 'Select the undefended ivory piece under attack.', 'An attack is a piece’s ability to capture on a square. Look along the violet bishop’s diagonal. Which ivory piece is in its path without a friend protecting it? This is an observation challenge, so select the piece instead of moving it.', [['g1','wk'],['d4','wr'],['b2','wp'],['g7','bb'],['a8','bk']], { type:'inspect', squares:['d4'] }, ['Trace the bishop’s diagonal down and left.', 'The diagonal is g7 → f6 → e5 → d4.', 'Select the rook on d4.'], 'The rook is attacked and undefended. Noticing danger is often more useful than searching for a brilliant move.', { mode:'inspect', concept:'threats' });
add(1, 'A free gift', 'Capture the undefended violet queen.', 'Before planning something complicated, look for a piece you can take safely. Your rook has a clear line to a very generous gift.', [['g1','wk'],['a1','wr'],['a7','bq'],['h8','bk']], { type:'safeCapture', square:'a7' }, ['The queen is on the same column as your rook.', 'No violet piece protects a7.', 'Move the rook from a1 to a7.'], 'You found a free queen. Always inspect what your opponent’s last move left undefended.', { concept:'capture' });
add(1, 'Look after a friend', 'Add a defender to the bishop on d4.', 'The violet rook attacks your bishop. Move your rook so it protects the bishop. If their rook takes it, your rook could capture back.', [['g1','wk'],['a1','wr'],['d4','wb'],['d8','br'],['h8','bk']], { type:'defend', square:'d4' }, ['A rook can protect a piece on the same row or column.', 'Either a4 or d1 gives your rook a line to d4.', 'Move a1 → a4, or a1 → d1.'], 'The bishop now has a defender. Protection does not forbid a capture—it gives you a way to capture back.', { allowed:['r'], concept:'defence' });
add(1, 'Is it really free?', 'Make a capture that leaves your rook safe.', 'There are two tempting captures. One target has a defender; the other does not. Inspect the violet pieces before choosing.', [['h1','wk'],['d4','wr'],['a4','bp'],['d7','bp'],['g7','br'],['h8','bk']], { type:'safeCapture' }, ['The violet rook on g7 protects the pawn on d7.', 'The pawn on a4 has no defender.', 'Move the rook from d4 to a4.'], 'A capture is not automatically a good deal. You checked the destination before taking the pawn.', { allowed:['r'], concept:'defence', refute:true });
add(1, 'Step out of trouble', 'Move your queen to a safe square.', 'The violet rook attacks your queen along the d-column. You can move away or capture the attacker if that is safe. There are several good answers.', [['g1','wk'],['d4','wq'],['d8','br'],['h8','bk']], { type:'safe', piece:'q' }, ['Find a destination outside the rook’s row and column.', 'A clear diagonal, such as e5, gets the queen away.', 'd4 → e5 is one safe answer. Capturing the rook on d8 also works.'], 'You saved the queen. Good chess often begins with keeping the pieces you already have.', { allowed:['q'], concept:'threats' });
add(1, 'Your move, their move', 'Capture the a5 pawn safely after a reply.', 'Chess players alternate turns. The violet rook currently protects a5. Make a useful waiting move and watch their reply, then reconsider the capture. Taking a5 immediately loses your rook.', [['g1','wk'],['a1','wr'],['a5','bp'],['h5','br'],['h8','bk']], { type:'safeCapture', square:'a5', minMoves:2 }, ['Your first move does not need to be a capture.', 'Try moving the rook to a4. Watch where their rook goes.', 'a1 → a4; after ...Rh7, play a4 → a5.'], 'You let the position change, then checked again. A plan must account for the opponent’s turn.', { maxMoves:2, concept:'turns', replies:['h5h7'], refute:true });
add(2, 'Meet the king', 'Move the king to g2.', 'The king moves one square in any direction. It must never move onto a square attacked by the opponent. Keeping it safe is the heart of chess.', [['h1','wk'],['e8','br'],['a8','bk']], { type:'reach', squares:['g2'] }, ['The lantern is one diagonal step away.', 'The rook attacks the e-column, not g2.', 'Move h1 → g2.'], 'The king is modest but essential. Kings also attack neighbouring squares, so opposing kings can never stand side by side.', { concept:'king', targets:['g2'] });
add(2, 'The king is in check', 'Select the king that is under attack.', '“Check” means a king is under attack. The player in check must remove that attack on their next move. Here, just find the king in trouble.', [['e1','wk'],['c1','wb'],['e8','br'],['a8','bk']], { type:'inspect', squares:['e1'] }, ['Look down the violet rook’s column.', 'The rook has a clear line from e8 to e1.', 'Select the ivory king on e1.'], 'That straight line is check. You may escape, block the attack, or capture the attacker—when those moves are legal.', { mode:'inspect', concept:'check' });
add(2, 'Find an escape', 'Get out of check in one move.', 'The king is attacked again. Find any legal way to remove the check. You can move the king, or put a piece between it and the attacking rook.', [['e1','wk'],['a2','wr'],['e8','br'],['h8','bk']], { type:'escape' }, ['A legal king move must leave the e-column.', 'd1 or f1 are possible escape squares. Blocking with Re2 also works.', 'Move the king e1 → d1, or move the rook a2 → e2.'], 'Check is a problem to solve, not the end of the game. Several different escapes can be equally valid.', { concept:'check' });
add(2, 'Put up a shield', 'Block the check with your rook.', 'A king need not always run. Sliding pieces can be stopped by placing another piece in their path. Use the rook to interrupt this attack.', [['d1','wk'],['b3','wr'],['d8','br'],['h8','bk']], { type:'escape', piece:'r' }, ['The attacking line is the d-column.', 'Your rook can reach d3 from b3.', 'Move the rook b3 → d3.'], 'The rook blocks the attack. A knight’s check cannot be blocked because a knight jumps over pieces.', { allowed:['r'], concept:'check' });
add(2, 'Your first checkmate', 'Give check with no legal escape.', 'Checkmate means the king is attacked and its side has no legal way to remove the check. Your king and queen can work together to close every escape.', [['f6','wk'],['g6','wq'],['h8','bk']], { type:'mate' }, ['The ivory king protects g7.', 'A queen on g7 checks h8 and covers g8 and h7.', 'Move the queen g6 → g7.'], 'Checkmate! The king is attacked, every escape is covered, and the checking queen is protected. The game ends; kings are never captured.', { concept:'mate' });
add(2, 'The quiet draw', 'Create stalemate: no moves, but no check.', 'Stalemate is different: the player to move has no legal move, but their king is NOT in check. That is a draw. Create one deliberately so you can recognise—and later avoid—it.', [['f7','wk'],['g5','wq'],['h8','bk']], { type:'stalemate' }, ['Leave h8 unattacked while covering all three neighbouring squares.', 'Your king covers g8 and g7. Your queen needs to cover h7.', 'Move the queen g5 → g6.'], 'Stalemate is a draw, even with an extra queen. To win, the final position must include check as well as no escape.', { concept:'stalemate' });
add(3, 'Two threats at once', 'Use your knight to attack the king and queen.', 'A fork attacks two pieces with one move. A check is especially useful: the opponent must deal with the king, giving you a chance to take the other piece next.', [['g1','wk'],['e5','wn'],['d8','bq'],['h8','bk']], { type:'fork', pieces:['k','q'] }, ['Look for a knight landing square that attacks both d8 and h8.', 'f7 is an L-shaped leap from e5.', 'Move the knight e5 → f7.'], 'The knight forks the king and queen. After the check is answered, the queen may be available to capture.', { allowed:['n'], concept:'fork' });
add(3, 'A piece that cannot leave', 'Pin the knight to its king.', 'A pin puts a piece between an attacker and something important. A piece pinned to its king cannot legally move if doing so exposes the king.', [['g1','wk'],['e2','wb'],['c6','bn'],['e8','bk']], { type:'pin', square:'c6' }, ['Line up your bishop, the knight on c6, and the king on e8.', 'The diagonal runs b5 → c6 → d7 → e8.', 'Move the bishop e2 → b5.'], 'The knight is pinned to its king. Its usual jumps would expose the king, so they are illegal in this position.', { allowed:['b'], concept:'pin' });
add(3, 'A surprise behind the king', 'Check the king with the queen behind it.', 'A skewer attacks the valuable piece in front. When it moves, the piece behind becomes exposed. Here the king must respond to check, uncovering the queen.', [['g1','wk'],['e2','wb'],['c6','bk'],['d7','bq']], { type:'skewer', square:'d7' }, ['Find the diagonal through c6 and d7.', 'A bishop on b5 would attack the king first, with the queen behind it.', 'Move the bishop e2 → b5.'], 'That is a skewer. Follow the opponent’s reply before capturing; your plan should always be checked against the new board.', { allowed:['b'], concept:'skewer' });
add(3, 'Bring a second friend', 'Win material over two moves.', 'Both your rook and bishop can capture the violet rook. Their bishop can capture back, but your second attacker can then recapture it. Follow the exchange through.', [['g1','wk'],['d1','wr'],['g2','wb'],['d5','br'],['g8','bb'],['h8','bk']], { type:'material', gain:300, minMoves:2 }, ['Count attackers on d5: you have two; they have one defender.', 'Capture on d5 with either your rook or bishop.', 'Try Rd1 → d5; after ...Bxd5, play Bg2 → d5.'], 'You followed the exchange to the end and came out ahead. Counting attackers and defenders helps, but always check the actual sequence.', { maxMoves:2, replies:['g8d5'], concept:'trade' });
add(3, 'The fair exchange', 'Trade your rook for their rook.', 'Pieces have rough values: pawn 1, knight and bishop about 3, rook 5, queen 9. A defended piece can still be a sensible capture when you exchange pieces of equal value.', [['g1','wk'],['d1','wr'],['d5','br'],['g8','bb'],['h8','bk']], { type:'trade', square:'d5' }, ['Your rook and their rook have equal approximate value.', 'Their bishop will capture your rook after the exchange.', 'Play Rd1 → d5 and watch ...Bxd5.'], 'One rook for one rook: an equal material exchange. Values are a guide, not a guarantee that a move is strategically best.', { replies:['g8d5'], concept:'trade' });
add(3, 'Read the board', 'Find a useful, safe capture.', 'No named tactic this time. Take a moment to inspect the whole board. You are looking for something you can capture without immediately losing your rook.', [['h1','wk'],['d4','wr'],['a4','bb'],['d7','bp'],['g7','br'],['h8','bk']], { type:'safeCapture' }, ['Ask which violet piece is undefended.', 'The rook on g7 protects d7; the bishop on a4 has no defender.', 'Move the rook d4 → a4.'], 'You spotted the opportunity without being told its name. That is the kind of observation you can bring to a real game.', { allowed:['r'], concept:'threats', refute:true });
add(4, 'A pawn’s last mile', 'Advance the pawn from e6 to e7.', 'A pawn that has already moved advances just one square at a time. It cannot repeat the two-square starting move, even when the path is clear.', [['g1','wk'],['e6','wp'],['h8','bk']], { type:'reach', squares:['e7'] }, ['The pawn is far from its starting row.', 'Its only forward step is e7.', 'Move e6 → e7.'], 'One step at a time. A pawn reaching the final row must become a queen, rook, bishop, or knight.', { allowed:['p'], concept:'pawn', targets:['e7'] });
add(4, 'A small piece, a big future', 'Promote your pawn.', 'Reach the final row and choose a new piece: queen, rook, bishop, or knight. A queen is usually the strongest choice, but all four promotions are legal.', [['g1','wk'],['a7','wp'],['h8','bk']], { type:'promotion' }, ['The pawn is one square from the final row.', 'Move to a8; then choose a piece.', 'Play a7 → a8 and choose any of the four promotion pieces.'], 'Your pawn has promoted! You can have more than one queen. Promotion is mandatory when a pawn reaches the final row.', { allowed:['p'], concept:'promotion', targets:['a8'] });
add(4, 'A home for the king', 'Castle toward the rook on h1.', 'Castling moves the king two squares toward a rook, and the rook to the square the king crossed. Both must be unmoved, the path clear, and the king cannot start in, pass through, or end in check.', P([['e1','wk'],['h1','wr'],['a2','wp'],['h2','wp'],['e8','bk'],['a8','br']], 'w','K'), { type:'castle', side:'king' }, ['Select the king, not the rook.', 'The king moves from e1 to g1; the rook follows to f1.', 'Move the king e1 → g1.'], 'Castled! Your king is on g1 and rook on f1. A rook being attacked does not itself prevent castling; the king’s path must be safe.', { concept:'castling', targets:['g1'] });
add(4, 'Make room, then castle', 'Clear the left path and castle queenside.', 'A castling rehearsal: your opponent waits while you clear the bishop and knight, then castle toward a1. Every square between king and rook must be empty—including b1.', P([['e1','wk'],['a1','wr'],['h1','wr'],['b1','wn'],['c1','wb'],['e8','bk']], 'w','KQ'), { type:'castle', side:'queen' }, ['Move the knight away from b1, then move the bishop away from c1.', 'Try Nb1 → c3, then Bc1 → f4.', 'With b1, c1, and d1 empty, move the king e1 → c1.'], 'Queenside castling puts the king on c1 and rook on d1. You cleared the entire space between king and rook.', { mode:'drill', maxMoves:99, concept:'castling', targets:['c1'] });
add(4, 'The passing pawn', 'Capture the passing pawn en passant.', 'The violet pawn has just moved d7 → d5, landing beside your pawn. On this immediate reply only, you may capture it as if it had moved one square: move e5 → d6 and remove the pawn on d5.', P([['e1','wk'],['e5','wp'],['d5','bp'],['h8','bk']], 'w','', 'd6'), { type:'enPassant' }, ['This special capture is available only immediately after the two-square pawn move.', 'The destination is the empty square d6, not d5.', 'Move e5 → d6. The violet pawn on d5 will disappear.'], 'En passant means “in passing.” If you choose a different move, the opportunity expires.', { allowed:['p'], concept:'enPassant', targets:['d6'] });
add(5, 'Claim the centre', 'Advance either centre pawn two squares.', 'A real starting position! White moves first. Pawns in the centre help control important squares and open paths for bishops and the queen. Try either e4 or d4.', START, { type:'reach', squares:['e4','d4'], piece:'p' }, ['The centre pawns begin on d2 and e2.', 'Choose either one; there is more than one good opening.', 'Move e2 → e4, or d2 → d4.'], 'A useful opening idea: influence the centre and give your pieces room. You do not need to memorise an opening to begin playing.', { concept:'opening', targets:['e4','d4'] });
let opening = applyMove(fromFEN(START), { from:index('e2'), to:index('e4') });
opening = applyMove(opening, { from:index('e7'), to:index('e5') });
add(5, 'Bring a knight out', 'Develop a knight toward the centre.', 'After both players advance a centre pawn, bring a knight from its starting square to c3 or f3. “Develop” simply means getting your pieces into useful positions.', toFEN(opening), { type:'reach', squares:['c3','f3'], piece:'n' }, ['Knights on c3 and f3 influence central squares.', 'Choose the knight on b1 or g1.', 'Play Nb1 → c3, or Ng1 → f3.'], 'You developed a piece toward the centre. Usually, bring several pieces into play before moving the same one repeatedly.', { concept:'opening', targets:['c3','f3'] });
opening = applyMove(opening, { from:index('g1'), to:index('f3') });
opening = applyMove(opening, { from:index('b8'), to:index('c6') });
add(5, 'Give a bishop room', 'Develop the bishop on f1 to a safe square.', 'The e-pawn has opened a diagonal for your bishop. Find a safe destination, bring another piece into play, and make future castling possible.', toFEN(opening), { type:'reach', squares:['e2','d3','c4','b5'], piece:'b', safe:true }, ['The bishop on f1 has an open diagonal.', 'e2, d3, c4, and b5 are all useful safe choices here.', 'For example, move Bf1 → c4.'], 'You are building an opening plan: centre, development, then king safety. These principles matter more than knowing a long sequence of moves.', { allowed:['b'], concept:'opening' });
add(5, 'Finish with a rook', 'Checkmate with king and rook working together.', 'Your king covers the escape squares g7 and h7. The rook can control the entire final row. Use the two pieces as a team to finish the game.', [['g6','wk'],['a7','wr'],['h8','bk']], { type:'mate' }, ['Your king stops the opponent escaping downwards.', 'The rook needs to check along the eighth rank.', 'Move the rook a7 → a8.'], 'A rook can deliver checkmate with help from its king. Endgames reward cooperation between pieces, not just captures.', { allowed:['r'], concept:'mate' });
add(5, 'First light', 'Find a move that finishes the game.', 'The last lantern is yours to light. Inspect the king, the queen, and the opponent’s escapes. There is no new rule here—just a chance to use what you have learned.', [['c6','wk'],['e7','wq'],['a8','bk']], { type:'mate' }, ['Find a protected queen square that checks the king and covers its escapes.', 'Your king protects b7. A queen there covers a8, a7, and b8.', 'Move the queen e7 → b7.'], 'Checkmate—and first light at the observatory. You can move every piece, recognise threats, keep your king safe, and start an ordinary game. Keep exploring: every game has something to teach you.', { concept:'mate' });
export const LESSONS = lessons;
export const HANDBOOK = [
  ['rook','The rook','Rows and columns, any clear distance. Cannot jump. A rook is worth roughly 5 pawns.'],
  ['bishop','The bishop','Diagonals, any clear distance. Cannot jump. Each bishop stays on one square colour. Worth roughly 3 pawns.'],
  ['knight','The knight','An L-shaped leap: two squares one way, one to the side. Jumps over pieces. Worth roughly 3 pawns.'],
  ['queen','The queen','Rows, columns, and diagonals, any clear distance. Cannot jump. Worth roughly 9 pawns.'],
  ['pawn','The pawn','Moves one square forward into an empty square. May move two from its starting row if both squares are empty. Captures one square diagonally forward. Never backwards.'],
  ['king','The king','One square in any direction. Cannot move onto an attacked square. Opposing kings cannot be adjacent. The king is never captured.'],
  ['capture','Capturing','Move onto an enemy piece’s square and remove it. You cannot capture friendly pieces. Captures are optional unless they are the only legal escape from check.'],
  ['blockers','Clear paths','Rooks, bishops, and queens stop at the first occupied square. They may capture an enemy there. Only knights jump over pieces.'],
  ['turns','Taking turns','White moves first; then players alternate one move each. Movement drills are labelled and let you practise without an opponent.'],
  ['threats','Seeing danger','Inspect what the opponent can attack. A legal move can still lose a piece. Before moving, ask what changed and what could be captured next.'],
  ['defence','Protecting pieces','A defender could capture back if a friendly piece is taken. Protection does not make a square untouchable. Count and consider the actual exchange.'],
  ['check','Check','A king is attacked. The next move must remove the attack: move the king, capture the attacker, or block a sliding attack. You cannot ignore check.'],
  ['mate','Checkmate','The king is in check and its side has no legal way to remove it. That player loses immediately. Kings are never captured.'],
  ['stalemate','Stalemate & draws','No legal moves, but no check: stalemate, a draw. Games can also draw when no checkmate is possible, by repetition, or after many moves without a pawn move or capture.'],
  ['fork','The fork','One piece attacks two targets. A fork including check forces a response to the king first. Recheck the board after the opponent’s reply.'],
  ['pin','The pin','A piece shields something behind it. If that something is its king, moving away and exposing check is illegal. Other pins are strategic, not absolute.'],
  ['skewer','The skewer','A valuable piece is attacked with another behind it. After the first moves away, the piece behind may become a target.'],
  ['trade','Exchanges & values','Pawn ≈1; knight ≈3; bishop ≈3; rook ≈5; queen ≈9. Follow captures and recaptures through. King safety and position can matter more than points.'],
  ['promotion','Promotion','On reaching the final row, a pawn must become a queen, rook, bishop, or knight. Choose any of the four, even if you already have pieces of that kind.'],
  ['castling','Castling','King moves two squares toward an unmoved rook; rook moves to the square crossed. King and rook must be unmoved, every square between empty, and the king cannot start in, cross, or end in check.'],
  ['enPassant','En passant','Immediately after an opposing pawn moves two squares and lands beside your pawn, your pawn may capture it as if it moved one square. This chance lasts exactly one reply.'],
  ['opening','Your first plan','Influence the centre, develop knights and bishops, and keep your king safe. Look for opponent threats before following your own plan. Learn from games rather than memorising long openings.']
];
