// Official department names and codes verified against geo.api.gouv.fr/departements.
// Department-specific metadata is independent of the Regions pack; IDs use stable official codes.
export const DEPARTMENT_CARDS = [
  {
    "id": "departments-01",
    "deck": "departments",
    "index": 0,
    "code": "01",
    "name": "Ain",
    "subtitle": "01 · Bresse farms & Jura foothills",
    "dates": "Department created: 1790",
    "description": "French department 01 (Ain), in metropolitan France. Its illustrated local scene features Bresse farms and Jura foothills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections.webp",
    "atlasIndex": 0,
    "columns": 3,
    "rows": 2
  },
  {
    "id": "departments-02",
    "deck": "departments",
    "index": 1,
    "code": "02",
    "name": "Aisne",
    "subtitle": "02 · Laon cathedral & hilltop town",
    "dates": "Department created: 1790",
    "description": "French department 02 (Aisne), in metropolitan France. Its illustrated local scene features Laon cathedral and hilltop town. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-03",
    "deck": "departments",
    "index": 2,
    "code": "03",
    "name": "Allier",
    "subtitle": "03 · Bourbonnais towers & wooded hills",
    "dates": "Department created: 1790",
    "description": "French department 03 (Allier), in metropolitan France. Its illustrated local scene features Bourbonnais towers and wooded hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-04",
    "deck": "departments",
    "index": 3,
    "code": "04",
    "name": "Alpes-de-Haute-Provence",
    "subtitle": "04 · Valensole lavender fields",
    "dates": "Department created: 1790",
    "description": "French department 04 (Alpes-de-Haute-Provence), in metropolitan France. Its illustrated local scene features Valensole lavender fields. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections.webp",
    "atlasIndex": 1,
    "columns": 3,
    "rows": 2
  },
  {
    "id": "departments-05",
    "deck": "departments",
    "index": 4,
    "code": "05",
    "name": "Hautes-Alpes",
    "subtitle": "05 · Serre-Ponçon lake & Alpine peaks",
    "dates": "Department created: 1790",
    "description": "French department 05 (Hautes-Alpes), in metropolitan France. Its illustrated local scene features Serre-Ponçon lake and Alpine peaks. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-06",
    "deck": "departments",
    "index": 5,
    "code": "06",
    "name": "Alpes-Maritimes",
    "subtitle": "06 · Menton coast & citrus terraces",
    "dates": "Department created: 1860",
    "description": "French department 06 (Alpes-Maritimes), in metropolitan France. Its illustrated local scene features Menton coast and citrus terraces. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-07",
    "deck": "departments",
    "index": 6,
    "code": "07",
    "name": "Ardèche",
    "subtitle": "07 · Pont d’Arc & the Ardèche gorge",
    "dates": "Department created: 1790",
    "description": "French department 07 (Ardèche), in metropolitan France. Its illustrated local scene features Pont d’Arc and the Ardèche gorge. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-08",
    "deck": "departments",
    "index": 7,
    "code": "08",
    "name": "Ardennes",
    "subtitle": "08 · Place Ducale & Ardennes woods",
    "dates": "Department created: 1790",
    "description": "French department 08 (Ardennes), in metropolitan France. Its illustrated local scene features Place Ducale and Ardennes woods. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-09",
    "deck": "departments",
    "index": 8,
    "code": "09",
    "name": "Ariège",
    "subtitle": "09 · Foix castle & Pyrenean peaks",
    "dates": "Department created: 1790",
    "description": "French department 09 (Ariège), in metropolitan France. Its illustrated local scene features Foix castle and Pyrenean peaks. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-10",
    "deck": "departments",
    "index": 9,
    "code": "10",
    "name": "Aube",
    "subtitle": "10 · Troyes timbered houses & vineyards",
    "dates": "Department created: 1790",
    "description": "French department 10 (Aube), in metropolitan France. Its illustrated local scene features Troyes timbered houses and vineyards. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-01.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-11",
    "deck": "departments",
    "index": 10,
    "code": "11",
    "name": "Aude",
    "subtitle": "11 · Carcassonne walls & vineyard hills",
    "dates": "Department created: 1790",
    "description": "French department 11 (Aude), in metropolitan France. Its illustrated local scene features Carcassonne walls and vineyard hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-12",
    "deck": "departments",
    "index": 11,
    "code": "12",
    "name": "Aveyron",
    "subtitle": "12 · Millau viaduct & the Tarn valley",
    "dates": "Department created: 1790",
    "description": "French department 12 (Aveyron), in metropolitan France. Its illustrated local scene features Millau viaduct and the Tarn valley. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-13",
    "deck": "departments",
    "index": 12,
    "code": "13",
    "name": "Bouches-du-Rhône",
    "subtitle": "13 · Marseille harbour & limestone coast",
    "dates": "Department created: 1790",
    "description": "French department 13 (Bouches-du-Rhône), in metropolitan France. Its illustrated local scene features Marseille harbour and limestone coast. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-14",
    "deck": "departments",
    "index": 13,
    "code": "14",
    "name": "Calvados",
    "subtitle": "14 · Bayeux cathedral & Norman orchards",
    "dates": "Department created: 1790",
    "description": "French department 14 (Calvados), in metropolitan France. Its illustrated local scene features Bayeux cathedral and Norman orchards. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 3,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-15",
    "deck": "departments",
    "index": 14,
    "code": "15",
    "name": "Cantal",
    "subtitle": "15 · Puy Mary & volcanic pastures",
    "dates": "Department created: 1790",
    "description": "French department 15 (Cantal), in metropolitan France. Its illustrated local scene features Puy Mary and volcanic pastures. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-16",
    "deck": "departments",
    "index": 15,
    "code": "16",
    "name": "Charente",
    "subtitle": "16 · Cognac vineyards & copper still",
    "dates": "Department created: 1790",
    "description": "French department 16 (Charente), in metropolitan France. Its illustrated local scene features Cognac vineyards and copper still. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections.webp",
    "atlasIndex": 2,
    "columns": 3,
    "rows": 2
  },
  {
    "id": "departments-17",
    "deck": "departments",
    "index": 16,
    "code": "17",
    "name": "Charente-Maritime",
    "subtitle": "17 · La Rochelle towers & Atlantic marshes",
    "dates": "Department created: 1790",
    "description": "French department 17 (Charente-Maritime), in metropolitan France. Its illustrated local scene features La Rochelle towers and Atlantic marshes. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-18",
    "deck": "departments",
    "index": 17,
    "code": "18",
    "name": "Cher",
    "subtitle": "18 · Bourges marsh gardens",
    "dates": "Department created: 1790",
    "description": "French department 18 (Cher), in metropolitan France. Its illustrated local scene features Bourges marsh gardens. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections.webp",
    "atlasIndex": 3,
    "columns": 3,
    "rows": 2
  },
  {
    "id": "departments-19",
    "deck": "departments",
    "index": 18,
    "code": "19",
    "name": "Corrèze",
    "subtitle": "19 · Collonges-la-Rouge & chestnut hills",
    "dates": "Department created: 1790",
    "description": "French department 19 (Corrèze), in metropolitan France. Its illustrated local scene features Collonges-la-Rouge and chestnut hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-21",
    "deck": "departments",
    "index": 19,
    "code": "21",
    "name": "Côte-d'Or",
    "subtitle": "21 · Beaune glazed roofs & vineyards",
    "dates": "Department created: 1790",
    "description": "French department 21 (Côte-d'Or), in metropolitan France. Its illustrated local scene features Beaune glazed roofs and vineyards. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-02.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-22",
    "deck": "departments",
    "index": 20,
    "code": "22",
    "name": "Côtes-d'Armor",
    "subtitle": "22 · Pink granite coast & stone lighthouse",
    "dates": "Department created: 1790",
    "description": "French department 22 (Côtes-d'Armor), in metropolitan France. Its illustrated local scene features Pink granite coast and stone lighthouse. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-23",
    "deck": "departments",
    "index": 21,
    "code": "23",
    "name": "Creuse",
    "subtitle": "23 · Aubusson bridge & tapestry craft",
    "dates": "Department created: 1790",
    "description": "French department 23 (Creuse), in metropolitan France. Its illustrated local scene features Aubusson bridge and tapestry craft. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-24",
    "deck": "departments",
    "index": 22,
    "code": "24",
    "name": "Dordogne",
    "subtitle": "24 · Beynac castle & the Dordogne",
    "dates": "Department created: 1790",
    "description": "French department 24 (Dordogne), in metropolitan France. Its illustrated local scene features Beynac castle and the Dordogne. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-25",
    "deck": "departments",
    "index": 23,
    "code": "25",
    "name": "Doubs",
    "subtitle": "25 · Besançon citadel & the Doubs loop",
    "dates": "Department created: 1790",
    "description": "French department 25 (Doubs), in metropolitan France. Its illustrated local scene features Besançon citadel and the Doubs loop. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 3,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-26",
    "deck": "departments",
    "index": 24,
    "code": "26",
    "name": "Drôme",
    "subtitle": "26 · Grignan château & lavender fields",
    "dates": "Department created: 1790",
    "description": "French department 26 (Drôme), in metropolitan France. Its illustrated local scene features Grignan château and lavender fields. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-27",
    "deck": "departments",
    "index": 25,
    "code": "27",
    "name": "Eure",
    "subtitle": "27 · Giverny garden & lily ponds",
    "dates": "Department created: 1790",
    "description": "French department 27 (Eure), in metropolitan France. Its illustrated local scene features Giverny garden and lily ponds. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-28",
    "deck": "departments",
    "index": 26,
    "code": "28",
    "name": "Eure-et-Loir",
    "subtitle": "28 · Chartres spires & wheat fields",
    "dates": "Department created: 1790",
    "description": "French department 28 (Eure-et-Loir), in metropolitan France. Its illustrated local scene features Chartres spires and wheat fields. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-29",
    "deck": "departments",
    "index": 27,
    "code": "29",
    "name": "Finistère",
    "subtitle": "29 · Pointe du Raz & Atlantic cliffs",
    "dates": "Department created: 1790",
    "description": "French department 29 (Finistère), in metropolitan France. Its illustrated local scene features Pointe du Raz and Atlantic cliffs. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-2A",
    "deck": "departments",
    "index": 28,
    "code": "2A",
    "name": "Corse-du-Sud",
    "subtitle": "2A · Bonifacio cliffs & southern Corsica",
    "dates": "Department created: 1976",
    "description": "French department 2A (Corse-du-Sud), in metropolitan France. Its illustrated local scene features Bonifacio cliffs and southern Corsica. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-2B",
    "deck": "departments",
    "index": 29,
    "code": "2B",
    "name": "Haute-Corse",
    "subtitle": "2B · Bastia harbour & Cap Corse",
    "dates": "Department created: 1976",
    "description": "French department 2B (Haute-Corse), in metropolitan France. Its illustrated local scene features Bastia harbour and Cap Corse. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-03.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-30",
    "deck": "departments",
    "index": 30,
    "code": "30",
    "name": "Gard",
    "subtitle": "30 · Pont du Gard & olive groves",
    "dates": "Department created: 1790",
    "description": "French department 30 (Gard), in metropolitan France. Its illustrated local scene features Pont du Gard and olive groves. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-31",
    "deck": "departments",
    "index": 31,
    "code": "31",
    "name": "Haute-Garonne",
    "subtitle": "31 · Toulouse brickwork & the Garonne",
    "dates": "Department created: 1790",
    "description": "French department 31 (Haute-Garonne), in metropolitan France. Its illustrated local scene features Toulouse brickwork and the Garonne. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-32",
    "deck": "departments",
    "index": 32,
    "code": "32",
    "name": "Gers",
    "subtitle": "32 · Gascon sunflowers & windmill",
    "dates": "Department created: 1790",
    "description": "French department 32 (Gers), in metropolitan France. Its illustrated local scene features Gascon sunflowers and windmill. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections.webp",
    "atlasIndex": 4,
    "columns": 3,
    "rows": 2
  },
  {
    "id": "departments-33",
    "deck": "departments",
    "index": 33,
    "code": "33",
    "name": "Gironde",
    "subtitle": "33 · Dune du Pilat & Atlantic pines",
    "dates": "Department created: 1790",
    "description": "French department 33 (Gironde), in metropolitan France. Its illustrated local scene features Dune du Pilat and Atlantic pines. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 3,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-34",
    "deck": "departments",
    "index": 34,
    "code": "34",
    "name": "Hérault",
    "subtitle": "34 · Sète canals & the Thau lagoon",
    "dates": "Department created: 1790",
    "description": "French department 34 (Hérault), in metropolitan France. Its illustrated local scene features Sète canals and the Thau lagoon. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-35",
    "deck": "departments",
    "index": 35,
    "code": "35",
    "name": "Ille-et-Vilaine",
    "subtitle": "35 · Saint-Malo ramparts & tidal coast",
    "dates": "Department created: 1790",
    "description": "French department 35 (Ille-et-Vilaine), in metropolitan France. Its illustrated local scene features Saint-Malo ramparts and tidal coast. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-36",
    "deck": "departments",
    "index": 36,
    "code": "36",
    "name": "Indre",
    "subtitle": "36 · Brenne ponds & reed beds",
    "dates": "Department created: 1790",
    "description": "French department 36 (Indre), in metropolitan France. Its illustrated local scene features Brenne ponds and reed beds. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-37",
    "deck": "departments",
    "index": 37,
    "code": "37",
    "name": "Indre-et-Loire",
    "subtitle": "37 · Chenonceau gallery & the Cher",
    "dates": "Department created: 1790",
    "description": "French department 37 (Indre-et-Loire), in metropolitan France. Its illustrated local scene features Chenonceau gallery and the Cher. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-38",
    "deck": "departments",
    "index": 38,
    "code": "38",
    "name": "Isère",
    "subtitle": "38 · Grenoble cable cars & Alpine peaks",
    "dates": "Department created: 1790",
    "description": "French department 38 (Isère), in metropolitan France. Its illustrated local scene features Grenoble cable cars and Alpine peaks. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-39",
    "deck": "departments",
    "index": 39,
    "code": "39",
    "name": "Jura",
    "subtitle": "39 · Baume-les-Messieurs & limestone cliffs",
    "dates": "Department created: 1790",
    "description": "French department 39 (Jura), in metropolitan France. Its illustrated local scene features Baume-les-Messieurs and limestone cliffs. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-04.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-40",
    "deck": "departments",
    "index": 40,
    "code": "40",
    "name": "Landes",
    "subtitle": "40 · Atlantic dunes & maritime pines",
    "dates": "Department created: 1790",
    "description": "French department 40 (Landes), in metropolitan France. Its illustrated local scene features Atlantic dunes and maritime pines. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-41",
    "deck": "departments",
    "index": 41,
    "code": "41",
    "name": "Loir-et-Cher",
    "subtitle": "41 · Chambord towers & forest lawns",
    "dates": "Department created: 1790",
    "description": "French department 41 (Loir-et-Cher), in metropolitan France. Its illustrated local scene features Chambord towers and forest lawns. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-42",
    "deck": "departments",
    "index": 42,
    "code": "42",
    "name": "Loire",
    "subtitle": "42 · Couriot mine headframe & Loire hills",
    "dates": "Department created: 1793",
    "description": "French department 42 (Loire), in metropolitan France. Its illustrated local scene features Couriot mine headframe and Loire hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-43",
    "deck": "departments",
    "index": 43,
    "code": "43",
    "name": "Haute-Loire",
    "subtitle": "43 · Le Puy chapel & volcanic rock",
    "dates": "Department created: 1790",
    "description": "French department 43 (Haute-Loire), in metropolitan France. Its illustrated local scene features Le Puy chapel and volcanic rock. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections.webp",
    "atlasIndex": 5,
    "columns": 3,
    "rows": 2
  },
  {
    "id": "departments-44",
    "deck": "departments",
    "index": 44,
    "code": "44",
    "name": "Loire-Atlantique",
    "subtitle": "44 · Loire estuary bridge & salt marshes",
    "dates": "Department created: 1790",
    "description": "French department 44 (Loire-Atlantique), in metropolitan France. Its illustrated local scene features Loire estuary bridge and salt marshes. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-45",
    "deck": "departments",
    "index": 45,
    "code": "45",
    "name": "Loiret",
    "subtitle": "45 · Orléans cathedral & the Loire",
    "dates": "Department created: 1790",
    "description": "French department 45 (Loiret), in metropolitan France. Its illustrated local scene features Orléans cathedral and the Loire. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-46",
    "deck": "departments",
    "index": 46,
    "code": "46",
    "name": "Lot",
    "subtitle": "46 · Pont Valentré & the Lot",
    "dates": "Department created: 1790",
    "description": "French department 46 (Lot), in metropolitan France. Its illustrated local scene features Pont Valentré and the Lot. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-47",
    "deck": "departments",
    "index": 47,
    "code": "47",
    "name": "Lot-et-Garonne",
    "subtitle": "47 · Agen canal bridge & plum orchards",
    "dates": "Department created: 1790",
    "description": "French department 47 (Lot-et-Garonne), in metropolitan France. Its illustrated local scene features Agen canal bridge and plum orchards. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-48",
    "deck": "departments",
    "index": 48,
    "code": "48",
    "name": "Lozère",
    "subtitle": "48 · Tarn gorge & limestone villages",
    "dates": "Department created: 1790",
    "description": "French department 48 (Lozère), in metropolitan France. Its illustrated local scene features Tarn gorge and limestone villages. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-49",
    "deck": "departments",
    "index": 49,
    "code": "49",
    "name": "Maine-et-Loire",
    "subtitle": "49 · Angers castle & the Maine",
    "dates": "Department created: 1790",
    "description": "French department 49 (Maine-et-Loire), in metropolitan France. Its illustrated local scene features Angers castle and the Maine. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-05.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-50",
    "deck": "departments",
    "index": 50,
    "code": "50",
    "name": "Manche",
    "subtitle": "50 · Mont Saint-Michel & tidal sands",
    "dates": "Department created: 1790",
    "description": "French department 50 (Manche), in metropolitan France. Its illustrated local scene features Mont Saint-Michel and tidal sands. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-51",
    "deck": "departments",
    "index": 51,
    "code": "51",
    "name": "Marne",
    "subtitle": "51 · Reims cathedral & Champagne vines",
    "dates": "Department created: 1790",
    "description": "French department 51 (Marne), in metropolitan France. Its illustrated local scene features Reims cathedral and Champagne vines. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-52",
    "deck": "departments",
    "index": 52,
    "code": "52",
    "name": "Haute-Marne",
    "subtitle": "52 · Langres ramparts & wooded plateau",
    "dates": "Department created: 1790",
    "description": "French department 52 (Haute-Marne), in metropolitan France. Its illustrated local scene features Langres ramparts and wooded plateau. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-53",
    "deck": "departments",
    "index": 53,
    "code": "53",
    "name": "Mayenne",
    "subtitle": "53 · Laval castle & the Mayenne",
    "dates": "Department created: 1790",
    "description": "French department 53 (Mayenne), in metropolitan France. Its illustrated local scene features Laval castle and the Mayenne. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 3,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-54",
    "deck": "departments",
    "index": 54,
    "code": "54",
    "name": "Meurthe-et-Moselle",
    "subtitle": "54 · Place Stanislas & mirabelle orchards",
    "dates": "Department created: 1790",
    "description": "French department 54 (Meurthe-et-Moselle), in metropolitan France. Its illustrated local scene features Place Stanislas and mirabelle orchards. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-55",
    "deck": "departments",
    "index": 55,
    "code": "55",
    "name": "Meuse",
    "subtitle": "55 · Verdun gateway & the Meuse",
    "dates": "Department created: 1790",
    "description": "French department 55 (Meuse), in metropolitan France. Its illustrated local scene features Verdun gateway and the Meuse. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-56",
    "deck": "departments",
    "index": 56,
    "code": "56",
    "name": "Morbihan",
    "subtitle": "56 · Morbihan islands & standing stones",
    "dates": "Department created: 1790",
    "description": "French department 56 (Morbihan), in metropolitan France. Its illustrated local scene features Morbihan islands and standing stones. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-57",
    "deck": "departments",
    "index": 57,
    "code": "57",
    "name": "Moselle",
    "subtitle": "57 · Metz cathedral & the Moselle",
    "dates": "Department created: 1790",
    "description": "French department 57 (Moselle), in metropolitan France. Its illustrated local scene features Metz cathedral and the Moselle. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-58",
    "deck": "departments",
    "index": 58,
    "code": "58",
    "name": "Nièvre",
    "subtitle": "58 · Loire riverside & Nevers pottery",
    "dates": "Department created: 1790",
    "description": "French department 58 (Nièvre), in metropolitan France. Its illustrated local scene features Loire riverside and Nevers pottery. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections2.webp",
    "atlasIndex": 0,
    "columns": 3,
    "rows": 1
  },
  {
    "id": "departments-59",
    "deck": "departments",
    "index": 59,
    "code": "59",
    "name": "Nord",
    "subtitle": "59 · Lille Flemish facades & belfries",
    "dates": "Department created: 1790",
    "description": "French department 59 (Nord), in metropolitan France. Its illustrated local scene features Lille Flemish facades and belfries. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-06.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-60",
    "deck": "departments",
    "index": 60,
    "code": "60",
    "name": "Oise",
    "subtitle": "60 · Chantilly château & forest ponds",
    "dates": "Department created: 1790",
    "description": "French department 60 (Oise), in metropolitan France. Its illustrated local scene features Chantilly château and forest ponds. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-61",
    "deck": "departments",
    "index": 61,
    "code": "61",
    "name": "Orne",
    "subtitle": "61 · Bagnoles lake & Norman orchards",
    "dates": "Department created: 1790",
    "description": "French department 61 (Orne), in metropolitan France. Its illustrated local scene features Bagnoles lake and Norman orchards. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-62",
    "deck": "departments",
    "index": 62,
    "code": "62",
    "name": "Pas-de-Calais",
    "subtitle": "62 · Cap Blanc-Nez & Channel cliffs",
    "dates": "Department created: 1790",
    "description": "French department 62 (Pas-de-Calais), in metropolitan France. Its illustrated local scene features Cap Blanc-Nez and Channel cliffs. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-63",
    "deck": "departments",
    "index": 63,
    "code": "63",
    "name": "Puy-de-Dôme",
    "subtitle": "63 · Puy de Dôme & volcanic hills",
    "dates": "Department created: 1790",
    "description": "French department 63 (Puy-de-Dôme), in metropolitan France. Its illustrated local scene features Puy de Dôme and volcanic hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 3,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-64",
    "deck": "departments",
    "index": 64,
    "code": "64",
    "name": "Pyrénées-Atlantiques",
    "subtitle": "64 · Bayonne riverside & Basque hills",
    "dates": "Department created: 1790",
    "description": "French department 64 (Pyrénées-Atlantiques), in metropolitan France. Its illustrated local scene features Bayonne riverside and Basque hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-65",
    "deck": "departments",
    "index": 65,
    "code": "65",
    "name": "Hautes-Pyrénées",
    "subtitle": "65 · Gavarnie cirque & mountain waterfall",
    "dates": "Department created: 1790",
    "description": "French department 65 (Hautes-Pyrénées), in metropolitan France. Its illustrated local scene features Gavarnie cirque and mountain waterfall. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-66",
    "deck": "departments",
    "index": 66,
    "code": "66",
    "name": "Pyrénées-Orientales",
    "subtitle": "66 · Collioure harbour & Catalan coast",
    "dates": "Department created: 1790",
    "description": "French department 66 (Pyrénées-Orientales), in metropolitan France. Its illustrated local scene features Collioure harbour and Catalan coast. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-67",
    "deck": "departments",
    "index": 67,
    "code": "67",
    "name": "Bas-Rhin",
    "subtitle": "67 · Strasbourg canals & timbered houses",
    "dates": "Department created: 1790",
    "description": "French department 67 (Bas-Rhin), in metropolitan France. Its illustrated local scene features Strasbourg canals and timbered houses. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-68",
    "deck": "departments",
    "index": 68,
    "code": "68",
    "name": "Haut-Rhin",
    "subtitle": "68 · Colmar canals & vineyard slopes",
    "dates": "Department created: 1790",
    "description": "French department 68 (Haut-Rhin), in metropolitan France. Its illustrated local scene features Colmar canals and vineyard slopes. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-69",
    "deck": "departments",
    "index": 69,
    "code": "69",
    "name": "Rhône",
    "subtitle": "69 · Villefranche & Beaujolais vines",
    "dates": "Department created: 1793",
    "description": "French department 69 (Rhône), in metropolitan France. Its illustrated local scene features Villefranche and Beaujolais vines. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-07.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-70",
    "deck": "departments",
    "index": 70,
    "code": "70",
    "name": "Haute-Saône",
    "subtitle": "70 · Mille Étangs ponds & wooded hills",
    "dates": "Department created: 1790",
    "description": "French department 70 (Haute-Saône), in metropolitan France. Its illustrated local scene features Mille Étangs ponds and wooded hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections2.webp",
    "atlasIndex": 1,
    "columns": 3,
    "rows": 1
  },
  {
    "id": "departments-71",
    "deck": "departments",
    "index": 71,
    "code": "71",
    "name": "Saône-et-Loire",
    "subtitle": "71 · Solutré rock & Burgundy vines",
    "dates": "Department created: 1790",
    "description": "French department 71 (Saône-et-Loire), in metropolitan France. Its illustrated local scene features Solutré rock and Burgundy vines. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-72",
    "deck": "departments",
    "index": 72,
    "code": "72",
    "name": "Sarthe",
    "subtitle": "72 · Le Mans walls & the Sarthe",
    "dates": "Department created: 1790",
    "description": "French department 72 (Sarthe), in metropolitan France. Its illustrated local scene features Le Mans walls and the Sarthe. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-73",
    "deck": "departments",
    "index": 73,
    "code": "73",
    "name": "Savoie",
    "subtitle": "73 · Chambéry fountain & Alpine peaks",
    "dates": "Department created: 1860",
    "description": "French department 73 (Savoie), in metropolitan France. Its illustrated local scene features Chambéry fountain and Alpine peaks. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 3,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-74",
    "deck": "departments",
    "index": 74,
    "code": "74",
    "name": "Haute-Savoie",
    "subtitle": "74 · Lake Annecy & Alpine peaks",
    "dates": "Department created: 1860",
    "description": "French department 74 (Haute-Savoie), in metropolitan France. Its illustrated local scene features Lake Annecy and Alpine peaks. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-corrections2.webp",
    "atlasIndex": 2,
    "columns": 3,
    "rows": 1
  },
  {
    "id": "departments-75",
    "deck": "departments",
    "index": 75,
    "code": "75",
    "name": "Paris",
    "subtitle": "75 · Eiffel Tower & the Seine",
    "dates": "Department created: 1968",
    "description": "French department 75 (Paris), in metropolitan France. Its illustrated local scene features Eiffel Tower and the Seine. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-76",
    "deck": "departments",
    "index": 76,
    "code": "76",
    "name": "Seine-Maritime",
    "subtitle": "76 · Étretat arch & chalk coast",
    "dates": "Department created: 1790",
    "description": "French department 76 (Seine-Maritime), in metropolitan France. Its illustrated local scene features Étretat arch and chalk coast. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-77",
    "deck": "departments",
    "index": 77,
    "code": "77",
    "name": "Seine-et-Marne",
    "subtitle": "77 · Vaux-le-Vicomte & formal gardens",
    "dates": "Department created: 1790",
    "description": "French department 77 (Seine-et-Marne), in metropolitan France. Its illustrated local scene features Vaux-le-Vicomte and formal gardens. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-78",
    "deck": "departments",
    "index": 78,
    "code": "78",
    "name": "Yvelines",
    "subtitle": "78 · Versailles palace & formal gardens",
    "dates": "Department created: 1968",
    "description": "French department 78 (Yvelines), in metropolitan France. Its illustrated local scene features Versailles palace and formal gardens. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-79",
    "deck": "departments",
    "index": 79,
    "code": "79",
    "name": "Deux-Sèvres",
    "subtitle": "79 · Marais Poitevin canals & willows",
    "dates": "Department created: 1790",
    "description": "French department 79 (Deux-Sèvres), in metropolitan France. Its illustrated local scene features Marais Poitevin canals and willows. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-08.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-80",
    "deck": "departments",
    "index": 80,
    "code": "80",
    "name": "Somme",
    "subtitle": "80 · Amiens cathedral & water gardens",
    "dates": "Department created: 1790",
    "description": "French department 80 (Somme), in metropolitan France. Its illustrated local scene features Amiens cathedral and water gardens. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-81",
    "deck": "departments",
    "index": 81,
    "code": "81",
    "name": "Tarn",
    "subtitle": "81 · Albi brick cathedral & the Tarn",
    "dates": "Department created: 1790",
    "description": "French department 81 (Tarn), in metropolitan France. Its illustrated local scene features Albi brick cathedral and the Tarn. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-82",
    "deck": "departments",
    "index": 82,
    "code": "82",
    "name": "Tarn-et-Garonne",
    "subtitle": "82 · Montauban brick arcades & orchards",
    "dates": "Department created: 1808",
    "description": "French department 82 (Tarn-et-Garonne), in metropolitan France. Its illustrated local scene features Montauban brick arcades and orchards. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-83",
    "deck": "departments",
    "index": 83,
    "code": "83",
    "name": "Var",
    "subtitle": "83 · Toulon harbour & umbrella pines",
    "dates": "Department created: 1790",
    "description": "French department 83 (Var), in metropolitan France. Its illustrated local scene features Toulon harbour and umbrella pines. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 3,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-84",
    "deck": "departments",
    "index": 84,
    "code": "84",
    "name": "Vaucluse",
    "subtitle": "84 · Avignon papal palace & the Rhône",
    "dates": "Department created: 1793",
    "description": "French department 84 (Vaucluse), in metropolitan France. Its illustrated local scene features Avignon papal palace and the Rhône. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-85",
    "deck": "departments",
    "index": 85,
    "code": "85",
    "name": "Vendée",
    "subtitle": "85 · Tidal causeway & Atlantic island",
    "dates": "Department created: 1790",
    "description": "French department 85 (Vendée), in metropolitan France. Its illustrated local scene features Tidal causeway and Atlantic island. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-86",
    "deck": "departments",
    "index": 86,
    "code": "86",
    "name": "Vienne",
    "subtitle": "86 · Poitiers Romanesque facade & stone streets",
    "dates": "Department created: 1790",
    "description": "French department 86 (Vienne), in metropolitan France. Its illustrated local scene features Poitiers Romanesque facade and stone streets. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-87",
    "deck": "departments",
    "index": 87,
    "code": "87",
    "name": "Haute-Vienne",
    "subtitle": "87 · Limoges bridge & porcelain craft",
    "dates": "Department created: 1790",
    "description": "French department 87 (Haute-Vienne), in metropolitan France. Its illustrated local scene features Limoges bridge and porcelain craft. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-88",
    "deck": "departments",
    "index": 88,
    "code": "88",
    "name": "Vosges",
    "subtitle": "88 · Gérardmer lake & Vosges forest",
    "dates": "Department created: 1790",
    "description": "French department 88 (Vosges), in metropolitan France. Its illustrated local scene features Gérardmer lake and Vosges forest. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-89",
    "deck": "departments",
    "index": 89,
    "code": "89",
    "name": "Yonne",
    "subtitle": "89 · Auxerre riverside & vineyard hills",
    "dates": "Department created: 1790",
    "description": "French department 89 (Yonne), in metropolitan France. Its illustrated local scene features Auxerre riverside and vineyard hills. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-09.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-90",
    "deck": "departments",
    "index": 90,
    "code": "90",
    "name": "Territoire de Belfort",
    "subtitle": "90 · Belfort lion & citadel",
    "dates": "Department created: 1922",
    "description": "French department 90 (Territoire de Belfort), in metropolitan France. Its illustrated local scene features Belfort lion and citadel. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 0,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-91",
    "deck": "departments",
    "index": 91,
    "code": "91",
    "name": "Essonne",
    "subtitle": "91 · Milly market hall & woodland",
    "dates": "Department created: 1968",
    "description": "French department 91 (Essonne), in metropolitan France. Its illustrated local scene features Milly market hall and woodland. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 1,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-92",
    "deck": "departments",
    "index": 92,
    "code": "92",
    "name": "Hauts-de-Seine",
    "subtitle": "92 · Grande Arche & glass towers",
    "dates": "Department created: 1968",
    "description": "French department 92 (Hauts-de-Seine), in metropolitan France. Its illustrated local scene features Grande Arche and glass towers. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 2,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-93",
    "deck": "departments",
    "index": 93,
    "code": "93",
    "name": "Seine-Saint-Denis",
    "subtitle": "93 · Saint-Denis basilica & urban square",
    "dates": "Department created: 1968",
    "description": "French department 93 (Seine-Saint-Denis), in metropolitan France. Its illustrated local scene features Saint-Denis basilica and urban square. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-saint-denis.webp",
    "atlasIndex": 0,
    "columns": 1,
    "rows": 1
  },
  {
    "id": "departments-94",
    "deck": "departments",
    "index": 94,
    "code": "94",
    "name": "Val-de-Marne",
    "subtitle": "94 · Vincennes keep & woodland",
    "dates": "Department created: 1968",
    "description": "French department 94 (Val-de-Marne), in metropolitan France. Its illustrated local scene features Vincennes keep and woodland. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 4,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-95",
    "deck": "departments",
    "index": 95,
    "code": "95",
    "name": "Val-d'Oise",
    "subtitle": "95 · Auvers church & wheat fields",
    "dates": "Department created: 1968",
    "description": "French department 95 (Val-d'Oise), in metropolitan France. Its illustrated local scene features Auvers church and wheat fields. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 5,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-971",
    "deck": "departments",
    "index": 96,
    "code": "971",
    "name": "Guadeloupe",
    "subtitle": "971 · Pointe des Châteaux & tropical surf",
    "dates": "Department created: 1946",
    "description": "French department 971 (Guadeloupe), overseas. Its illustrated local scene features Pointe des Châteaux and tropical surf. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 6,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-972",
    "deck": "departments",
    "index": 97,
    "code": "972",
    "name": "Martinique",
    "subtitle": "972 · Saint-Pierre coast & Mount Pelée",
    "dates": "Department created: 1946",
    "description": "French department 972 (Martinique), overseas. Its illustrated local scene features Saint-Pierre coast and Mount Pelée. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 7,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-973",
    "deck": "departments",
    "index": 98,
    "code": "973",
    "name": "Guyane",
    "subtitle": "973 · Cayenne hill & Amazonian rivers",
    "dates": "Department created: 1946",
    "description": "French department 973 (Guyane), overseas. Its illustrated local scene features Cayenne hill and Amazonian rivers. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 8,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-974",
    "deck": "departments",
    "index": 99,
    "code": "974",
    "name": "La Réunion",
    "subtitle": "974 · Piton de la Fournaise & lava fields",
    "dates": "Department created: 1946",
    "description": "French department 974 (La Réunion), overseas. Its illustrated local scene features Piton de la Fournaise and lava fields. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-10.webp",
    "atlasIndex": 9,
    "columns": 5,
    "rows": 2
  },
  {
    "id": "departments-976",
    "deck": "departments",
    "index": 100,
    "code": "976",
    "name": "Mayotte",
    "subtitle": "976 · Mayotte lagoon & Mount Choungui",
    "dates": "Department created: 2011",
    "description": "French department 976 (Mayotte), overseas. Its illustrated local scene features Mayotte lagoon and Mount Choungui. The composition is symbolic, not a map of departmental boundaries.",
    "atlas": "assets/departments-11.webp",
    "atlasIndex": 0,
    "columns": 1,
    "rows": 1
  }
];
