// Public card context. Dates are lifespans unless explicitly labelled otherwise.
// Approximate, traditional and mythological information is identified in the text.
// Editorial conventions and references: ../CARD_CONTEXT.md.
const entries = [
  ['Vercingetorix', 'c. 80–46 BCE', 'Arvernian leader who united Gallic resistance to Julius Caesar and surrendered after the siege of Alesia in 52 BCE.'],
  ['Clovis', 'c. 466–511', 'Merovingian ruler who united much of the Frankish kingdom and converted to Catholic Christianity.'],
  ['Charlemagne', 'Reign 768–814', 'Frankish king crowned emperor in Rome in 800; his court supported learning during the Carolingian Renaissance.'],
  ['Eleanor of Aquitaine', 'c. 1122–1204', 'Duchess of Aquitaine and queen of both France and England, associated with medieval court culture and powerful dynastic alliances.'],
  ['Louis IX', '1214–1270', 'French king later canonized as Saint Louis; his reign is associated with royal justice, Sainte-Chapelle and the Crusades.'],
  ['Joan of Arc', 'c. 1412–1431', 'Young French military figure who helped lift the siege of Orléans in 1429 during the Hundred Years’ War.'],
  ['Francis I', '1494–1547', 'Renaissance king of France who patronized the arts, welcomed Leonardo da Vinci and commissioned the château of Chambord.'],
  ['Catherine de Medici', '1519–1589', 'Italian-born queen and regent of France whose political influence spanned the French Wars of Religion.'],
  ['Henry IV', '1553–1610', 'First Bourbon king of France; the Edict of Nantes in 1598 granted limited religious toleration to French Protestants.'],
  ['Cardinal Richelieu', '1585–1642', 'Chief minister to Louis XIII who strengthened royal authority and helped shape France’s role in European politics.'],
  ['Louis XIV', '1638–1715', 'The Sun King ruled France for more than seventy years and made Versailles the center of his royal court.'],
  ['Molière', '1622–1673', 'French actor and playwright whose comedies, including Tartuffe, satirized hypocrisy and social pretension.'],
  ['Voltaire', '1694–1778', 'French Enlightenment writer known for Candide and for criticizing religious intolerance through satire and public debate.'],
  ['Émilie du Châtelet', '1706–1749', 'French mathematician and physicist who translated and explained Newton’s Principia for French readers.'],
  ['Marie Antoinette', '1755–1793', 'Austrian-born queen of France, married to Louis XVI; she was executed during the French Revolution.'],
  ['Olympe de Gouges', '1748–1793', 'French writer who published the Declaration of the Rights of Woman and of the Female Citizen in 1791.'],
  ['Robespierre', '1758–1794', 'French revolutionary and prominent Jacobin, associated with the Committee of Public Safety and the Reign of Terror.'],
  ['Napoleon', '1769–1821', 'French general and emperor whose campaigns reshaped Europe; the Napoleonic Code became an influential model of civil law.'],
  ['Joséphine', '1763–1814', 'Martinique-born first wife of Napoleon and empress of the French, known for her gardens and patronage at Malmaison.'],
  ['Victor Hugo', '1802–1885', 'French poet and novelist who wrote Les Misérables and The Hunchback of Notre-Dame and spent years in political exile.'],
  ['Louis Pasteur', '1822–1895', 'French scientist whose work on microbes, fermentation and vaccination helped transform medicine and food preservation.'],
  ['Marie Curie', '1867–1934', 'Polish-born scientist working in France who studied radioactivity and shared in the discovery of polonium and radium.'],
  ['Joséphine Baker', '1906–1975', 'American-born performer who became a French citizen, aided the Resistance and campaigned against racial discrimination.'],
  ['Charles de Gaulle', '1890–1970', 'Leader of Free France during World War II and a founder of the Fifth Republic, established in 1958.'],
  ['Cleopatra', '69–30 BCE', 'Last active ruler of Egypt’s Ptolemaic dynasty, known for her alliances with Julius Caesar and Mark Antony.'],
  ['Julius Caesar', '100–44 BCE', 'Roman general and statesman whose conquest of Gaul and rise to dictatorship helped end the Roman Republic.'],
  ['Hatshepsut', 'Reign c. 1473–1458 BCE', 'Female pharaoh of Egypt’s Eighteenth Dynasty, associated with trade expeditions and her terraced temple at Deir el-Bahri.'],
  ['Alexander the Great', '356–323 BCE', 'Macedonian king whose campaigns overthrew the Persian Empire and spread Greek cultural influence across a vast territory.'],
  ['Confucius', 'Trad. 551–479 BCE', 'Chinese teacher associated with ethics, ritual and responsible government; his teachings were transmitted in the Analects.'],
  ['Qin Shi Huang', '259–210 BCE', 'First emperor of a unified China, ruling from 221 BCE; his tomb complex contains the Terracotta Army.'],
  ['Mansa Musa', 'Reign c. 1312–1337', 'Ruler of the Mali Empire whose pilgrimage to Mecca in 1324 became famous for its display of gold and wealth.'],
  ['Genghis Khan', 'c. 1162–1227', 'Founder of the Mongol Empire who united Mongolian groups and led campaigns across large parts of Eurasia.'],
  ['Saladin', '1137/38–1193', 'Founder of the Ayyubid dynasty, known for recapturing Jerusalem in 1187 and his role in the Crusades.'],
  ['Ibn Battuta', 'c. 1304–1368/69', 'Moroccan traveler whose account describes journeys across North Africa, Asia and other parts of the medieval Islamic world.'],
  ['Zheng He', '1371–c. 1433', 'Ming admiral who led large maritime expeditions through the Indian Ocean between 1405 and 1433.'],
  ['Pachacuti', 'Reign c. 1438–1471', 'Inca ruler associated with the expansion of the empire from Cusco; the conventional dates of his reign are approximate.'],
  ['Leonardo da Vinci', '1452–1519', 'Italian Renaissance artist and investigator of anatomy, engineering and nature, known for the Mona Lisa and his notebooks.'],
  ['Elizabeth I', '1533–1603', 'Tudor queen of England whose reign saw the defeat of the Spanish Armada and the flourishing of English theater.'],
  ['William Shakespeare', '1564–1616', 'English playwright and poet whose tragedies, comedies and histories include Hamlet, Macbeth and A Midsummer Night’s Dream.'],
  ['Isaac Newton', '1643–1727', 'English mathematician and physicist who developed laws of motion and universal gravitation and investigated light and calculus.'],
  ['Ada Lovelace', '1815–1852', 'English mathematician whose notes on Charles Babbage’s Analytical Engine included an algorithm and a broader vision of computing.'],
  ['Harriet Tubman', 'c. 1822–1913', 'American abolitionist who escaped slavery and repeatedly guided other enslaved people to freedom through the Underground Railroad.'],
  ['Frederick Douglass', 'c. 1818–1895', 'American abolitionist, orator and writer whose autobiographies described slavery and whose speeches argued for equal rights.'],
  ['Mahatma Gandhi', '1869–1948', 'Indian independence leader associated with nonviolent resistance, civil disobedience and the Salt March of 1930.'],
  ['Frida Kahlo', '1907–1954', 'Mexican painter known for self-portraits that explore identity, bodily pain and Mexican cultural imagery.'],
  ['Albert Einstein', '1879–1955', 'Physicist who developed special and general relativity and received the Nobel Prize for explaining the photoelectric effect.'],
  ['Nelson Mandela', '1918–2013', 'South African anti-apartheid leader who became president after the country’s first fully inclusive national elections in 1994.'],
  ['Wangari Maathai', '1940–2011', 'Kenyan environmentalist who founded the Green Belt Movement and received the Nobel Peace Prize in 2004.'],
  ['Archimedes', 'c. 287–212 BCE', 'Greek mathematician from Syracuse associated with geometry, buoyancy and mechanical inventions such as the Archimedean screw.'],
  ['Hypatia', 'c. 350/370–415 CE', 'Alexandrian teacher of mathematics, astronomy and Neoplatonic philosophy; proposed birth dates range from about 350 to 370 CE.'],
  ['Al-Khwarizmi', 'c. 780–850', 'Scholar working in Abbasid Baghdad whose mathematical writings helped establish algebra; his name gave rise to the word algorithm.'],
  ['Ibn al-Haytham', 'c. 965–1040', 'Scholar known for experimental investigations of vision and light, including the explanation that light enters the eyes.'],
  ['Galileo Galilei', '1564–1642', 'Italian astronomer and physicist whose telescopic observations supported a Sun-centered model of the planetary system.'],
  ['Michael Faraday', '1791–1867', 'British experimental scientist who discovered electromagnetic induction, a principle central to electric generators and transformers.'],
  ['James Clerk Maxwell', '1831–1879', 'Scottish physicist whose equations unified electricity, magnetism and light within a theory of electromagnetism.'],
  ['Charles Darwin', '1809–1882', 'British naturalist who developed evolution by natural selection and published On the Origin of Species in 1859.'],
  ['Nikola Tesla', '1856–1943', 'Serbian-American inventor and electrical engineer associated with alternating-current motors and power systems.'],
  ['Emmy Noether', '1882–1935', 'German mathematician whose work reshaped abstract algebra; her theorem connects symmetries with conservation laws in physics.'],
  ['Srinivasa Ramanujan', '1887–1920', 'Indian mathematician known for original discoveries in number theory, infinite series and partitions.'],
  ['Alan Turing', '1912–1954', 'British mathematician who helped establish theoretical computing and contributed to codebreaking at Bletchley Park during World War II.'],
  ['Grace Hopper', '1906–1992', 'American mathematician, computing pioneer and naval officer who developed early compiler tools and helped shape COBOL.'],
  ['Rosalind Franklin', '1920–1958', 'British chemist whose X-ray diffraction research provided crucial evidence about DNA’s structure; she also studied coal and viruses.'],
  ['Katherine Johnson', '1918–2020', 'American mathematician whose calculations at NASA supported orbital spaceflight, including John Glenn’s mission and the Apollo program.'],
  ['Chien-Shiung Wu', '1912–1997', 'Chinese-American experimental physicist whose research demonstrated that parity is not conserved in certain weak interactions.'],
  ['Hedy Lamarr', '1914–2000', 'Austrian-born actor and inventor who co-developed a frequency-hopping communication system with composer George Antheil.'],
  ['Socrates', 'c. 469–399 BCE', 'Athenian philosopher known for questioning assumptions through dialogue; his ideas survive chiefly through accounts written by others.'],
  ['Plato', 'c. 428–348 BCE', 'Greek philosopher, student of Socrates and founder of the Academy; his dialogues examine justice, knowledge and ideal forms.'],
  ['Aristotle', '384–322 BCE', 'Greek philosopher and student of Plato whose writings cover logic, ethics, politics, biology and many other fields.'],
  ['Epicurus', '341–270 BCE', 'Greek philosopher who taught that a good life involves friendship, freedom from fear and the pursuit of modest pleasures.'],
  ['Diogenes', 'c. 412–323 BCE', 'Greek Cynic philosopher associated with an austere life and stories that challenge social conventions and material ambition.'],
  ['Laozi', 'Trad. 6th century BCE', 'Traditional Daoist sage associated with the Daodejing; his historical identity and the text’s authorship and dating are disputed.'],
  ['Zhuangzi', 'c. 369–286 BCE', 'Chinese Daoist thinker associated with imaginative parables, including the butterfly dream, that question fixed perspectives.'],
  ['Mencius', 'c. 372–289 BCE', 'Confucian philosopher known for arguing that human nature tends toward goodness and that rulers have moral responsibilities.'],
  ['Nāgārjuna', 'c. 150–250 CE', 'Indian Buddhist philosopher associated with the Madhyamaka school and the analysis of emptiness and dependent origination.'],
  ['Ibn Sina', '980–1037', 'Persian philosopher and physician, also called Avicenna, whose Canon of Medicine influenced medical teaching for centuries.'],
  ['Ibn Rushd', '1126–1198', 'Andalusian philosopher and physician, also called Averroes, known for influential commentaries on Aristotle.'],
  ['Thomas Aquinas', 'c. 1225–1274', 'Medieval Dominican theologian and philosopher who combined Christian theology with ideas drawn from Aristotle.'],
  ['Niccolò Machiavelli', '1469–1527', 'Florentine political thinker whose book The Prince examines power, leadership and the practical conduct of government.'],
  ['René Descartes', '1596–1650', 'French philosopher and mathematician associated with systematic doubt, mind-body dualism and the development of analytic geometry.'],
  ['Baruch Spinoza', '1632–1677', 'Dutch philosopher whose Ethics presents a system linking God, nature, human emotions and freedom.'],
  ['John Locke', '1632–1704', 'English philosopher associated with empiricism, natural rights and government based on the consent of the governed.'],
  ['David Hume', '1711–1776', 'Scottish philosopher whose writings examine experience, causation and the limits of what human reason can establish.'],
  ['Immanuel Kant', '1724–1804', 'German philosopher whose work explores how knowledge is possible and grounds moral duty in principles of practical reason.'],
  ['Mary Wollstonecraft', '1759–1797', 'English writer who argued for women’s education and equal moral standing in A Vindication of the Rights of Woman.'],
  ['Friedrich Nietzsche', '1844–1900', 'German philosopher whose works challenge inherited values and explore morality, culture and the creation of meaning.'],
  ['Simone de Beauvoir', '1908–1986', 'French existentialist philosopher and writer whose book The Second Sex became a major work of feminist thought.'],
  ['Hannah Arendt', '1906–1975', 'German-born political thinker who examined totalitarianism, public action and the responsibilities of individual judgment.'],
  ['Homer', 'Trad. 8th century BCE', 'Traditional Greek poet associated with the Iliad and Odyssey; his identity and the composition of the epics remain debated.'],
  ['Sappho', 'c. 630–570 BCE', 'Greek lyric poet from Lesbos whose surviving fragments explore desire, relationships and personal experience.'],
  ['Dante Alighieri', '1265–1321', 'Florentine poet whose Divine Comedy imagines a journey through Hell, Purgatory and Paradise.'],
  ['Geoffrey Chaucer', 'c. 1343–1400', 'English poet whose Canterbury Tales presents stories told by pilgrims traveling toward Canterbury.'],
  ['Miguel de Cervantes', '1547–1616', 'Spanish writer whose Don Quixote follows a would-be knight and his companion through comic and reflective adventures.'],
  ['Jean de La Fontaine', '1621–1695', 'French poet best known for fables that use animals and everyday situations to examine human behavior.'],
  ['Johann Wolfgang von Goethe', '1749–1832', 'German poet, novelist and thinker whose works include Faust and The Sorrows of Young Werther.'],
  ['Jane Austen', '1775–1817', 'English novelist who explored courtship, class and judgment through books such as Pride and Prejudice and Emma.'],
  ['Mary Shelley', '1797–1851', 'English novelist who published Frankenstein in 1818, a story about creation, responsibility and rejection.'],
  ['Alexandre Dumas', '1802–1870', 'French novelist known for historical adventures including The Three Musketeers and The Count of Monte Cristo.'],
  ['George Sand', '1804–1876', 'Pen name of French novelist Aurore Dupin, whose work and public life challenged expectations about women’s independence.'],
  ['Fyodor Dostoevsky', '1821–1881', 'Russian novelist whose books, including Crime and Punishment, explore guilt, faith, freedom and moral conflict.'],
  ['Leo Tolstoy', '1828–1910', 'Russian writer of War and Peace and Anna Karenina, later associated with religious and ethical ideas about nonviolence.'],
  ['Charles Dickens', '1812–1870', 'English novelist whose vivid characters and social criticism appear in Oliver Twist, A Christmas Carol and other works.'],
  ['Oscar Wilde', '1854–1900', 'Irish writer known for witty plays, The Picture of Dorian Gray and his association with the aesthetic movement.'],
  ['Virginia Woolf', '1882–1941', 'English modernist novelist whose writing experiments with consciousness and time; she also argued for women’s creative independence.'],
  ['Franz Kafka', '1883–1924', 'Prague-born writer whose stories, including The Metamorphosis and The Trial, depict unsettling transformations and opaque authority.'],
  ['Rabindranath Tagore', '1861–1941', 'Bengali poet, composer and educator who received the Nobel Prize in Literature in 1913.'],
  ['Jorge Luis Borges', '1899–1986', 'Argentine writer whose short fiction explores labyrinths, mirrors, imaginary books and the boundaries of reality.'],
  ['Toni Morrison', '1931–2019', 'American novelist whose books, including Beloved, examine Black life, memory and the legacy of slavery.'],
  ['Édith Piaf', '1915–1963', 'French chanson singer whose dramatic delivery made songs such as La Vie en rose internationally recognizable.'],
  ['Charles Aznavour', '1924–2018', 'French-Armenian singer and songwriter known for expressive storytelling and performances in several languages.'],
  ['Jacques Brel', '1929–1978', 'Belgian songwriter whose intensely theatrical performances brought songs such as Ne me quitte pas to a wide audience.'],
  ['Barbara', '1930–1997', 'French singer-songwriter and pianist known for intimate performances and songs such as L’Aigle noir.'],
  ['Georges Brassens', '1921–1981', 'French singer-songwriter whose guitar-accompanied songs combine poetry, wit and skepticism toward authority.'],
  ['Johnny Hallyday', '1943–2017', 'French performer who helped popularize rock and roll in France and became known for large, energetic stage shows.'],
  ['Michael Jackson', '1958–2009', 'American performer known for pop music, elaborate choreography and the album Thriller, released in 1982.'],
  ['Prince', '1958–2016', 'American singer, multi-instrumentalist and songwriter whose music combined funk, rock and pop; Purple Rain appeared in 1984.'],
  ['Freddie Mercury', '1946–1991', 'Queen’s lead singer, born in Zanzibar, known for a powerful voice and theatrical performances; he wrote Bohemian Rhapsody.'],
  ['Beyoncé', 'Born 1981', 'American singer and performer who rose to prominence with Destiny’s Child before a solo career spanning pop and R&B.'],
  ['Adele', 'Born 1988', 'British singer-songwriter known for a soulful voice and albums titled 19, 21, 25 and 30.'],
  ['Taylor Swift', 'Born 1989', 'American songwriter whose recording career moved from country into pop and other styles, often using autobiographical storytelling.'],
  ['Aretha Franklin', '1942–2018', 'American singer and pianist associated with soul and gospel, whose recording of Respect became a cultural anthem.'],
  ['Whitney Houston', '1963–2012', 'American singer and actor known for a powerful voice and her recording of I Will Always Love You.'],
  ['Nina Simone', '1933–2003', 'American pianist and singer who combined jazz, classical and other traditions and became associated with the civil rights movement.'],
  ['Ella Fitzgerald', '1917–1996', 'American jazz vocalist celebrated for scat singing and recordings of the Great American Songbook.'],
  ['Bob Marley', '1945–1981', 'Jamaican musician who helped bring reggae and Rastafarian themes to an international audience with the Wailers.'],
  ['Elvis Presley', '1935–1977', 'American singer whose recordings and performances helped popularize rock and roll during the 1950s.'],
  ['David Bowie', '1947–2016', 'British musician and actor known for changing musical styles and stage identities, including Ziggy Stardust.'],
  ['Shakira', 'Born 1977', 'Colombian singer-songwriter whose music combines Latin pop, rock and dance influences; she records in Spanish and English.'],
  ['Céline Dion', 'Born 1968', 'Quebec-born singer known for French and English recordings, including My Heart Will Go On from Titanic.'],
  ['Björk', 'Born 1965', 'Icelandic singer and composer whose work combines an expressive voice, electronic experimentation and striking visual design.'],
  ['Stromae', 'Born 1985', 'Belgian singer and producer whose French-language songs combine electronic dance music with reflections on social and personal life.'],
  ['Bad Bunny', 'Born 1994', 'Puerto Rican artist associated with Latin trap and reggaeton, known for Spanish-language music and distinctive fashion.'],
  ['Charlie Chaplin', '1889–1977', 'British actor and filmmaker whose silent-film character the Tramp uses physical comedy to explore hardship and human dignity.'],
  ['Buster Keaton', '1895–1966', 'American silent-film actor and director known for a deadpan expression, physical comedy and elaborate practical stunts.'],
  ['Marilyn Monroe', '1926–1962', 'American actor and singer associated with Hollywood’s studio era, including the comedy Some Like It Hot.'],
  ['Audrey Hepburn', '1929–1993', 'British actor known for Roman Holiday and Breakfast at Tiffany’s who later worked as a UNICEF goodwill ambassador.'],
  ['James Dean', '1931–1955', 'American actor whose short career included Rebel Without a Cause and East of Eden, both released in 1955.'],
  ['Marlon Brando', '1924–2004', 'American actor associated with method acting, known for A Streetcar Named Desire, On the Waterfront and The Godfather.'],
  ['Alain Delon', '1935–2024', 'French actor known for cool, enigmatic screen roles in films such as Le Samouraï and Purple Noon.'],
  ['Jean-Paul Belmondo', '1933–2021', 'French actor who starred in Breathless and later became known for action films, comedy and performing his own stunts.'],
  ['Catherine Deneuve', 'Born 1943', 'French actor known for The Umbrellas of Cherbourg, Belle de Jour and a long career in European cinema.'],
  ['Louis de Funès', '1914–1983', 'French comedy actor known for rapid gestures, expressive reactions and films including La Grande Vadrouille.'],
  ['Omar Sy', 'Born 1978', 'French actor who gained international recognition through The Intouchables and later played the lead in Lupin.'],
  ['Marion Cotillard', 'Born 1975', 'French actor whose portrayal of Édith Piaf in La Vie en Rose brought international recognition and an Academy Award.'],
  ['Meryl Streep', 'Born 1949', 'American actor known for varied dramatic and comic roles, including Sophie’s Choice and The Devil Wears Prada.'],
  ['Robert De Niro', 'Born 1943', 'American actor associated with films such as Taxi Driver, Raging Bull and The Godfather Part II.'],
  ['Morgan Freeman', 'Born 1937', 'American actor known for The Shawshank Redemption, Driving Miss Daisy and a distinctive voice used in narration.'],
  ['Denzel Washington', 'Born 1954', 'American actor and director whose roles include Malcolm X and Training Day, alongside work in theater.'],
  ['Keanu Reeves', 'Born 1964', 'Canadian actor, born in Beirut, known for action and science-fiction roles including The Matrix and John Wick.'],
  ['Michelle Yeoh', 'Born 1962', 'Malaysian actor known for martial-arts cinema and films including Crouching Tiger, Hidden Dragon and Everything Everywhere All at Once.'],
  ['Jackie Chan', 'Born 1954', 'Hong Kong actor and filmmaker known for combining martial arts, physical comedy and elaborate stunt work.'],
  ['Bruce Lee', '1940–1973', 'Actor and martial artist who developed Jeet Kune Do and helped bring Hong Kong action cinema to international audiences.'],
  ['Shah Rukh Khan', 'Born 1965', 'Indian actor associated with Hindi cinema, known for romantic and dramatic roles including Dilwale Dulhania Le Jayenge.'],
  ['Amitabh Bachchan', 'Born 1942', 'Indian actor whose 1970s Hindi-film roles helped establish the screen image of the angry young man.'],
  ['Viola Davis', 'Born 1965', 'American actor known for work across theater, film and television, including Fences and How to Get Away with Murder.'],
  ['Tilda Swinton', 'Born 1960', 'Scottish actor known for distinctive performances in independent and mainstream films, including Orlando and Michael Clayton.'],
  ['Paris', 'Eiffel Tower: 1889', 'French capital on the Seine, associated with art, fashion and the Eiffel Tower, built for the 1889 World’s Fair.'],
  ['Rome', 'Colosseum: 80 CE', 'Italian capital and former center of the Roman Empire; the Colosseum was inaugurated under Emperor Titus in 80 CE.'],
  ['London', 'Big Ben: 1859', 'British capital on the Thames; the Great Bell and clock at Westminster began operating in 1859.'],
  ['Berlin', 'Brandenburg Gate: 1791', 'German capital whose Brandenburg Gate became a symbol of division during the Cold War and reunification after 1989.'],
  ['Tokyo', 'Renamed Tokyo: 1868', 'Japan’s capital was formerly called Edo; it was renamed Tokyo during the Meiji transition in 1868.'],
  ['New York City', 'Renamed New York: 1664', 'American port city on the Hudson, renamed from New Amsterdam in 1664 and known for Manhattan’s skyline.'],
  ['Amsterdam', 'First recorded: 1275', 'Dutch capital known for canals and gabled houses; its first surviving written mention appears in a toll privilege from 1275.'],
  ['Venice', 'Republic ended: 1797', 'Italian lagoon city known for canals and gondolas; its long-lived maritime republic ended during Napoleon’s campaigns in 1797.'],
  ['Barcelona', 'Sagrada Família: 1882–', 'Mediterranean city in Catalonia, known for modernist architecture; construction of the Sagrada Família began in 1882.'],
  ['Athens', 'Parthenon: 447–432 BCE', 'Greek capital associated with ancient philosophy and democracy; the Parthenon stands on the Acropolis above the city.'],
  ['Istanbul', 'Ottoman conquest: 1453', 'City spanning the Bosphorus, formerly Constantinople, whose history connects Byzantine, Ottoman and modern Turkish cultures.'],
  ['Moscow', 'First recorded: 1147', 'Russian capital associated with the Kremlin and Saint Basil’s Cathedral; its first written mention is conventionally dated to 1147.'],
  ['Cairo', 'Founded: 969', 'Egyptian capital near the Nile; the Fatimid city was founded in 969, while nearby Giza’s pyramids are much older.'],
  ['Marrakesh', 'Founded c. 1070–1072', 'Moroccan imperial city founded by the Almoravids, known for its medina, markets and red-toned buildings.'],
  ['Dubai', 'Burj Khalifa: 2010', 'City in the United Arab Emirates whose skyline includes the Burj Khalifa, inaugurated in 2010, alongside a historic trading creek.'],
  ['Mumbai', 'Gateway of India: 1924', 'Indian port city formerly called Bombay, associated with Hindi cinema and the Gateway of India monument.'],
  ['Beijing', 'Temple of Heaven: 1420', 'Chinese capital whose Temple of Heaven complex was completed in 1420; its iconic blue-roofed hall was rebuilt later.'],
  ['Seoul', 'Joseon capital: 1394', 'South Korean capital on the Han River, known for royal palaces and a history as the Joseon dynasty’s capital.'],
  ['Singapore', 'Independence: 1965', 'Island city-state in Southeast Asia known for its port, multicultural neighborhoods and the Merlion symbol.'],
  ['Sydney', 'Opera House: 1973', 'Australian harbor city whose sail-shaped Opera House opened in 1973; it is not Australia’s national capital.'],
  ['Rio de Janeiro', 'Christ statue: 1931', 'Brazilian coastal city known for Carnival, Sugarloaf Mountain and Christ the Redeemer, inaugurated in 1931.'],
  ['Mexico City', 'Tenochtitlan: trad. 1325', 'Mexican capital built over the former Mexica city of Tenochtitlan; the traditional founding date refers to that earlier city.'],
  ['Cape Town', 'Dutch settlement: 1652', 'South African coastal city beneath Table Mountain; 1652 marks a Dutch colonial settlement, not the beginning of local habitation.'],
  ['San Francisco', 'Golden Gate Bridge: 1937', 'American city known for steep hills, cable cars and the Golden Gate Bridge, opened in 1937.'],
  ['France', 'First Republic: 1792', 'European country associated with the French Revolution; 1792 marks the First Republic, not the beginning of French history.'],
  ['Italy', 'Unification: 1861', 'Mediterranean country whose modern kingdom was proclaimed in 1861; Rome became the national capital in 1871.'],
  ['United Kingdom', 'Act of Union: 1801', 'The union of Great Britain and Ireland took effect in 1801; the country’s territory and name changed subsequently.'],
  ['Germany', 'Reunification: 1990', 'Central European country divided after World War II and reunified in 1990, with landscapes ranging from coasts to the Alps.'],
  ['Spain', 'Constitution: 1978', 'European country with varied regional cultures; its democratic constitution dates to 1978, long after its medieval kingdoms.'],
  ['Greece', 'Independence recognized: 1830', 'Mediterranean country associated with ancient Greek civilization; 1830 marks recognition of the modern state’s independence.'],
  ['Norway', 'Independence: 1905', 'Nordic country known for fjords and northern landscapes; its union with Sweden ended in 1905.'],
  ['Japan', 'Meiji Restoration: 1868', 'East Asian island country whose Meiji Restoration began in 1868; Mount Fuji and torii gates are familiar cultural symbols.'],
  ['China', 'People’s Republic: 1949', 'East Asian country with a long imperial history; 1949 marks the founding of the People’s Republic, not Chinese civilization.'],
  ['India', 'Independence: 1947', 'South Asian country that gained independence from British rule in 1947, known for varied languages, religions and landscapes.'],
  ['South Korea', 'Republic established: 1948', 'Country on the southern Korean Peninsula whose republic was established in 1948; traditional palaces coexist with modern cities.'],
  ['Indonesia', 'Independence declared: 1945', 'Southeast Asian archipelago whose independence was proclaimed in 1945; Dutch recognition followed in 1949.'],
  ['Turkey', 'Republic proclaimed: 1923', 'Country spanning Europe and Asia whose republic was proclaimed in 1923 after the dissolution of the Ottoman Empire.'],
  ['Saudi Arabia', 'Kingdom unified: 1932', 'Arabian Peninsula country unified under its present kingdom in 1932, associated with desert landscapes and the holy cities of Islam.'],
  ['Egypt', 'Republic proclaimed: 1953', 'Country centered on the Nile and known for ancient pharaonic monuments; 1953 marks the modern republic, not ancient Egypt.'],
  ['Morocco', 'Independence: 1956', 'North African country whose French protectorate ended in 1956, known for imperial cities, the Atlas Mountains and varied coastlines.'],
  ['Kenya', 'Independence: 1963', 'East African country that gained independence from Britain in 1963, with landscapes including savannas, highlands and the Indian Ocean coast.'],
  ['South Africa', 'Inclusive elections: 1994', 'Country at Africa’s southern tip whose first fully inclusive national elections in 1994 marked the end of apartheid government.'],
  ['United States', 'Independence declared: 1776', 'North American country whose Declaration of Independence dates to 1776; its landscapes range from deserts to forests and coastlines.'],
  ['Canada', 'Confederation: 1867', 'North American country whose confederation began in 1867, known for extensive forests, lakes and northern landscapes.'],
  ['Mexico', 'Independence achieved: 1821', 'North American country whose independence from Spain was achieved in 1821 after a war that began in 1810.'],
  ['Brazil', 'Independence: 1822', 'South American country that declared independence from Portugal in 1822, associated with the Amazon, Atlantic coast and Carnival.'],
  ['Australia', 'Federation: 1901', 'Country whose colonies federated in 1901; Aboriginal and Torres Strait Islander histories long predate colonization and federation.'],
  ['New Zealand', 'Dominion status: 1907', 'Pacific country granted Dominion status in 1907, with Māori and later settler histories and landscapes of mountains and fjords.'],
  ['Auvergne-Rhône-Alpes', 'Regional merger: 2016', 'Region formed by merging Auvergne and Rhône-Alpes, bringing together volcanic uplands, Lyon and the French Alps.'],
  ['Bourgogne-Franche-Comté', 'Regional merger: 2016', 'Region formed by merging Bourgogne and Franche-Comté, associated with vineyards, Jura landscapes and traditional tiled roofs.'],
  ['Bretagne', 'Union with France: 1532', 'Atlantic region with Breton and Gallo cultural traditions; 1532 refers to the union of the duchy of Brittany with France.'],
  ['Centre-Val de Loire', 'Chambord begun: 1519', 'Loire Valley region known for royal châteaux; Francis I commissioned Chambord, whose construction began in 1519.'],
  ['Corse', 'Single collectivity: 2018', 'Mediterranean island with a distinct Corsican culture; a single territorial collectivity replaced its previous regional and departmental bodies in 2018.'],
  ['Grand Est', 'Regional merger: 2016', 'Region formed from Alsace, Champagne-Ardenne and Lorraine, spanning vineyards, timbered towns and borders with several European countries.'],
  ['Hauts-de-France', 'Regional merger: 2016', 'Northern region formed from Nord-Pas-de-Calais and Picardie, associated with belfries, Gothic cathedrals and Channel coastlines.'],
  ['Île-de-France', 'Court at Versailles: 1682', 'Region surrounding Paris; Louis XIV established his court at Versailles in 1682, connecting the region with royal and urban history.'],
  ['Normandie', 'Regional reunification: 2016', 'Region reunited from Haute-Normandie and Basse-Normandie, known for Channel cliffs, apple orchards and medieval Norman history.'],
  ['Nouvelle-Aquitaine', 'Regional merger: 2016', 'Region formed from Aquitaine, Limousin and Poitou-Charentes, stretching from Atlantic dunes and vineyards to inland uplands.'],
  ['Occitanie', 'Regional merger: 2016', 'Region formed from Languedoc-Roussillon and Midi-Pyrénées, with Toulouse, medieval towns and Mediterranean and Pyrenean landscapes.'],
  ['Pays de la Loire', 'Planning region: 1956', 'Western region organized as a planning region in 1956, associated with Nantes, the lower Loire and Atlantic coast.'],
  ['Provence-Alpes-Côte d’Azur', 'Avignon papacy: 1309–1377', 'Southeastern region linking Alpine mountains, Provençal landscapes and the Mediterranean; Avignon hosted the papacy during the fourteenth century.'],
  ['Guadeloupe', 'Department status: 1946', 'Caribbean archipelago and French overseas region, known for La Soufrière volcano and tropical coasts; it became a department in 1946.'],
  ['Martinique', 'Department status: 1946', 'Caribbean island and French overseas region, associated with Mount Pelée, Creole culture and sugarcane; departmental status dates to 1946.'],
  ['Guyane', 'Department status: 1946', 'French overseas region on South America’s mainland, with Amazonian forests and the spaceport at Kourou; it became a department in 1946.'],
  ['La Réunion', 'Department status: 1946', 'French overseas island in the Indian Ocean, known for volcanic landscapes and Creole culture; departmental status dates to 1946.'],
  ['Mayotte', 'Department status: 2011', 'French overseas region in the Comoros archipelago, associated with a large lagoon and mangroves; it became a department in 2011.'],
  ['Alsace', 'Historic · Grand Est since 2016', 'Historic cultural region associated with Strasbourg, Colmar, timbered houses and storks; its former administrative region joined Grand Est in 2016.'],
  ['Lorraine', 'Historic · Grand Est since 2016', 'Historic region associated with Nancy, Metz and mirabelle plums; its former administrative region joined Grand Est in 2016.'],
  ['Bourgogne', 'Historic · merged in 2016', 'Historic Burgundy is known for vineyards, abbeys and ducal history; its former administrative region joined Bourgogne-Franche-Comté in 2016.'],
  ['Champagne', 'Historic · fairs in 12th–13th c.', 'Historic region associated with medieval trade fairs and sparkling wine; it is not identical to the former Champagne-Ardenne administrative region.'],
  ['Picardie', 'Historic · merged in 2016', 'Historic region associated with Amiens and the Somme; its former administrative region joined Hauts-de-France in 2016.'],
  ['Auvergne', 'Historic · merged in 2016', 'Historic region associated with the Massif Central and dormant volcanoes; its former administrative region joined Auvergne-Rhône-Alpes in 2016.'],
  ['Zeus', 'Ancient Greek myth', 'Olympian king of the gods, associated with the sky, thunder and the lightning bolt; brother of Poseidon and Hades.'],
  ['Hera', 'Ancient Greek myth', 'Olympian goddess associated with marriage and queenship, often represented with a crown or peacock and married to Zeus.'],
  ['Poseidon', 'Ancient Greek myth', 'God of the sea, earthquakes and horses, commonly represented with a trident; brother of Zeus and Hades.'],
  ['Demeter', 'Ancient Greek myth', 'Goddess of grain and agriculture whose story with her daughter Persephone connects to the changing seasons.'],
  ['Athena', 'Ancient Greek myth', 'Goddess associated with wisdom, crafts and strategic warfare, commonly represented with armor and an owl.'],
  ['Apollo', 'Ancient Greek myth', 'God associated with music, prophecy and healing, linked to the lyre and the oracle at Delphi; twin of Artemis.'],
  ['Artemis', 'Ancient Greek myth', 'Goddess associated with hunting and wild animals, commonly represented with a bow and deer; twin of Apollo.'],
  ['Ares', 'Ancient Greek myth', 'God associated with war and battle, commonly represented with weapons and armor; linked in myth with Aphrodite.'],
  ['Aphrodite', 'Ancient Greek myth', 'Goddess associated with love and beauty; a famous tradition describes her birth from sea foam.'],
  ['Hephaestus', 'Ancient Greek myth', 'God of metalworking and the forge, associated with hammers, fire and crafted objects made for gods and heroes.'],
  ['Hermes', 'Ancient Greek myth', 'Messenger of the gods, associated with travel, trade and guiding souls; often represented with winged sandals or a winged hat.'],
  ['Dionysus', 'Ancient Greek myth', 'God associated with wine, ecstasy and theater, commonly represented with ivy, grapevines and a drinking cup.'],
  ['Hades', 'Ancient Greek myth', 'Ruler of the underworld, brother of Zeus and Poseidon and husband of Persephone; he is distinct from the personification of death.'],
  ['Persephone', 'Ancient Greek myth', 'Daughter of Demeter and queen of the underworld; pomegranates and her seasonal return are central to her story.'],
  ['Hestia', 'Ancient Greek myth', 'Goddess of the hearth and domestic life, associated with the household flame and the shared hearth of the community.'],
  ['Heracles', 'Ancient Greek myth', 'Hero associated with the twelve labors, immense strength, a lion skin and a club; known as Hercules in Roman tradition.'],
  ['Achilles', 'Myth · Trojan War', 'Greek hero of the Iliad whose conflict with Agamemnon and grief over Patroclus are central to the poem.'],
  ['Odysseus', 'Myth · Trojan War', 'King of Ithaca and central hero of the Odyssey, known for ingenuity and a long journey home after the Trojan War.'],
  ['Medusa', 'Ancient Greek myth', 'Snake-haired Gorgon whose gaze turns people to stone; Perseus defeats her in a famous Greek heroic story.'],
  ['Minotaur', 'Ancient Greek myth', 'Bull-headed creature of the Cretan labyrinth, defeated by Theseus with help from Ariadne.'],
  ['Pegasus', 'Ancient Greek myth', 'Winged horse associated with the birth from Medusa’s blood and with the hero Bellerophon.'],
  ['Cerberus', 'Ancient Greek myth', 'Multi-headed hound guarding the underworld, usually shown with three heads; capturing him is one of Heracles’ labors.'],
  ['Orpheus', 'Ancient Greek myth', 'Legendary musician who descends to the underworld to retrieve Eurydice, using the power of his music.'],
  ['Ariadne', 'Ancient Greek myth', 'Cretan princess who helps Theseus navigate the labyrinth with a thread; later traditions connect her with Dionysus.'],
];

export const CARD_CONTEXT = Object.fromEntries(entries.map(([name, dates, description]) => [name, {dates, description}]));

// A single administrative division: all regions as they stood on 31 December 2015.
export const REGION_2015_CONTEXT = Object.fromEntries([
  ['Alsace', 'Separate region until 2015', 'Eastern region bordering Germany, with Strasbourg as its capital, Colmar canals, half-timbered houses and stork imagery. It joined Grand Est in 2016.'],
  ['Aquitaine', 'Separate region until 2015', 'Southwestern region centered on Bordeaux, with Atlantic dunes, Landes pine forests, vineyards and a Basque coastline. It joined Nouvelle-Aquitaine in 2016.'],
  ['Auvergne', 'Separate region until 2015', 'Central upland region centered on Clermont-Ferrand, known for the Chaîne des Puys volcanoes, lava-stone churches and green pastures. It joined Auvergne-Rhône-Alpes in 2016.'],
  ['Basse-Normandie', 'Separate region until 2015', 'Western Norman region centered on Caen, including Mont Saint-Michel, the Cotentin peninsula and apple-growing countryside. It merged with Haute-Normandie to form Normandie in 2016.'],
  ['Bourgogne', 'Separate region until 2015', 'Eastern inland region centered on Dijon, known for Burgundy vineyards, stone abbeys and wine-growing villages. It joined Bourgogne-Franche-Comté in 2016.'],
  ['Bretagne', 'Union with France: 1532', 'Atlantic region centered on Rennes, with Breton and Gallo traditions, rocky coasts and lighthouses. Its 2015 boundaries remained after the reform; 1532 refers to the duchy’s union with France.'],
  ['Centre-Val de Loire', 'Renamed: 2015', 'Region centered on Orléans, known for the Loire and royal châteaux such as Chambord. Previously called Centre, it became Centre-Val de Loire in January 2015; its boundaries remained after the 2016 reform.'],
  ['Champagne-Ardenne', 'Separate region until 2015', 'Northeastern region centered on Châlons-en-Champagne, combining Reims, champagne vineyards and Ardennes forests. It joined Grand Est in 2016.'],
  ['Corse', '2015 territorial division', 'Mediterranean island and territorial collectivity centered on Ajaccio, with mountain landscapes, turquoise bays and Genoese coastal towers. It was one of the 22 metropolitan regions in the 2015 division.'],
  ['Franche-Comté', 'Separate region until 2015', 'Eastern region centered on Besançon, with the Doubs river, Jura mountains, fortified architecture and Comté cheese. It joined Bourgogne-Franche-Comté in 2016.'],
  ['Haute-Normandie', 'Separate region until 2015', 'Eastern Norman region centered on Rouen, with Seine valleys, timbered towns and Étretat’s chalk cliffs. It merged with Basse-Normandie to form Normandie in 2016.'],
  ['Île-de-France', 'Court at Versailles: 1682', 'Region surrounding Paris, with Versailles and the capital’s urban landmarks. Its 2015 boundaries remained after the reform; Louis XIV established his court at Versailles in 1682.'],
  ['Languedoc-Roussillon', 'Separate region until 2015', 'Southern region centered on Montpellier, with Mediterranean lagoons, Carcassonne’s fortified walls, vineyards and the Roussillon plain. It joined Occitanie in 2016.'],
  ['Limousin', 'Separate region until 2015', 'Central-western region centered on Limoges, associated with porcelain, chestnut forests and villages such as Collonges-la-Rouge. It joined Nouvelle-Aquitaine in 2016.'],
  ['Lorraine', 'Separate region until 2015', 'Northeastern region centered on Metz, with Nancy’s Place Stanislas, mirabelle plums and borders with Belgium, Luxembourg and Germany. It joined Grand Est in 2016.'],
  ['Midi-Pyrénées', 'Separate region until 2015', 'Southwestern inland region centered on Toulouse, spanning the Garonne valley, red-brick towns and Pyrenean mountains. It joined Occitanie in 2016.'],
  ['Nord-Pas-de-Calais', 'Separate region until 2015', 'Northern region centered on Lille, associated with Arras belfries, mining spoil heaps and Channel and North Sea coasts. It joined Hauts-de-France in 2016.'],
  ['Pays de la Loire', 'Planning region: 1956', 'Western region centered on Nantes, combining the lower Loire, Atlantic shores and inland landscapes. Its 2015 boundaries remained after the 2016 reform.'],
  ['Picardie', 'Separate region until 2015', 'Northern region centered on Amiens, with Gothic cathedrals, agricultural plains and Somme Bay wetlands. It joined Hauts-de-France in 2016.'],
  ['Poitou-Charentes', 'Separate region until 2015', 'Western region centered on Poitiers, including La Rochelle’s harbor towers, Marais Poitevin waterways and Charente vineyards. It joined Nouvelle-Aquitaine in 2016.'],
  ['Provence-Alpes-Côte d’Azur', 'Avignon papacy: 1309–1377', 'Southeastern region centered on Marseille, linking Provençal lavender fields, Alpine mountains and the Mediterranean. Its 2015 boundaries remained after the reform; Avignon hosted the medieval papacy.'],
  ['Rhône-Alpes', 'Separate region until 2015', 'Southeastern region centered on Lyon, with the Rhône valley, Alpine ski areas and Mont Blanc. It joined Auvergne-Rhône-Alpes in 2016.'],
  ['Guadeloupe', 'Department status: 1946', 'Caribbean archipelago and one of France’s five overseas regions in 2015, with La Soufrière volcano, tropical waterfalls and turquoise coasts. Department status dates to 1946.'],
  ['Guyane', 'Department status: 1946', 'South American territory and one of France’s five overseas regions in 2015, known for Amazonian forest, broad rivers and the Kourou space center. Department status dates to 1946.'],
  ['Martinique', 'Department status: 1946', 'Caribbean island and one of France’s five overseas regions in 2015, with Mount Pelée, Creole coastal towns and sugarcane landscapes. Department status dates to 1946.'],
  ['La Réunion', 'Department status: 1946', 'Indian Ocean island and one of France’s five overseas regions in 2015, known for Piton de la Fournaise, mountainous cirques and tropical coasts. Department status dates to 1946.'],
  ['Mayotte', 'Department status: 2011', 'Indian Ocean islands in the Comoros archipelago and one of France’s five overseas regions in 2015, with a large lagoon, mangroves and sea turtles. Department status dates to 2011.'],
].map(([name,dates,description])=>[name,{dates,description}]));
