// Offline campaign verifier / par finder.
//   node tools/solve.mjs            solve every level, print par + timing
//   node tools/solve.mjs w2-3       solve one level
//   node tools/solve.mjs --write    also write src/solutions.js (par + a replayable solution)
import fs from 'node:fs';
import { WORLDS } from '../src/campaign.js';
import { solve, drain } from '../src/solver.js';
import { createWorld, replay } from '../src/physics.js';
import { placeStarsAlong } from '../src/generator.js';

const args = process.argv.slice(2);
const write = args.includes('--write');
const only = args.filter((a) => !a.startsWith('--'));
const maxDepth = Number((args.find((a) => a.startsWith('--depth=')) || '--depth=3').split('=')[1]);
const out = {};
for (const w of WORLDS) {
  for (const level of w.levels) {
    if (only.length && !only.includes(level.id)) continue;
    const t0 = Date.now();
    const r = drain(solve(level, { maxDepth }));
    const ms = Date.now() - t0;
    if (!r) {
      console.log(`${level.id.padEnd(6)} ${level.name.padEnd(22)} NO SOLUTION in ${maxDepth} shots  (${ms}ms)`);
      continue;
    }
    const shots = r.shots.map((s) => ({ t: s.t, angle: s.angle, power: s.power })); // full precision so replays are exact
    const stars = level.starFracs ? placeStarsAlong(level, shots, level.starFracs) : [];
    const withStars = { ...level, stars };
    const S = replay(createWorld(withStars), shots);
    const ok = S.ball.mode === 'captured' && S.shots === r.par && S.starsGot === stars.length;
    console.log(`${level.id.padEnd(6)} ${level.name.padEnd(22)} par ${r.par}${level.par && level.par !== r.par ? ` (authored ${level.par})` : ''}  ${ok ? 'ok' : 'REPLAY FAILED'}  pickups ${S.starsGot}/${stars.length}  ${ms}ms`);
    out[level.id] = { par: r.par, shots, stars };
  }
}
if (write) {
  const body = `// Generated by tools/solve.mjs: do not edit by hand.\nexport const SOLUTIONS = ${JSON.stringify(out, null, 1)};\n`;
  fs.writeFileSync(new URL('../src/solutions.js', import.meta.url), body);
  console.log('wrote src/solutions.js');
}
