// Cards whose Wikidata item has no matching date, checked by hand against the
// linked article. The note names the exact event the year refers to.
export const REVIEWED = {
  'inv-first-telescope-patent': 'Lippershey applies for a patent, 2 October 1608',
  'inv-fahrenheit-temperature-scale': 'Fahrenheit\'s paper in the Philosophical Transactions, 1724',
  'inv-jenner-s-first-smallpox-vaccination': 'James Phipps inoculated, 14 May 1796',
  'inv-first-steam-railway-locomotive': 'Penydarren locomotive run, 21 February 1804',
  'inv-tin-can': 'Peter Durand patent, 1810',
  'inv-metronome': 'Maelzel patent, 1815',
  'inv-stethoscope': 'Laennec, 1816',
  'inv-first-morse-telegraph-message': '"What hath God wrought", 24 May 1844',
  'inv-safety-pin': 'Walter Hunt patent, 10 April 1849',
  'inv-riveted-blue-jeans': 'Davis and Strauss patent, 20 May 1873',
  'inv-ferris-wheel': 'World\'s Columbian Exposition, June 1893',
  'inv-transatlantic-radio-signal': 'Signal received at St John\'s, 12 December 1901',
  'inv-neon-lighting': 'Georges Claude, Paris Motor Show, December 1910',
  'inv-television-demonstrated-by-baird': 'Demonstration in London, 26 January 1926',
  'inv-biro-s-ballpoint-pen-patent': 'László Bíró\'s patent, 1938',
  'inv-transistor': 'Point-contact transistor at Bell Labs, December 1947',
  'inv-polaroid-instant-camera': 'Polaroid Model 95 on sale, November 1948',
  'inv-integrated-circuit': 'Kilby\'s first working circuit, 12 September 1958',
  'inv-hovercraft-sr-n1': 'First flight, 11 June 1959',
  'inv-first-mobile-phone-call': 'Martin Cooper\'s call, 3 April 1973',
  'inv-first-barcode-scanned-at-a-till': 'First UPC scan in Troy, Ohio, 26 June 1974',
  'inv-compact-disc-goes-on-sale': 'First CDs sold in Japan, 1 October 1982',
  'sci-galileo-discovers-jupiter-s-moons': 'Observations of January 1610',
  'sci-ohm-s-law': 'Die galvanische Kette published, 1827',
  'sci-electromagnetic-induction': 'Faraday\'s experiments, August 1831',
  'sci-maxwell-s-equations-of-electromagnetism': 'Paper published, 1865',
  'sci-mendeleev-s-periodic-table': 'Mendeleev\'s table, March 1869',
  'sci-pasteur-s-rabies-vaccine': 'Joseph Meister treated, July 1885',
  'sci-radio-waves-produced-by-hertz': 'Hertz\'s experiments, 1887',
  'sci-x-rays-discovered': 'Röntgen, 8 November 1895',
  'sci-radioactivity-discovered': 'Becquerel, March 1896',
  'sci-planck-s-quantum-hypothesis': 'Planck\'s lecture, 14 December 1900',
  'sci-blood-groups-discovered': 'Landsteiner, 1901',
  'sci-atomic-nucleus-discovered': 'Rutherford\'s paper, May 1911',
  'sci-continental-drift-proposed': 'Wegener\'s lecture, January 1912',
  'sci-general-relativity': 'Einstein\'s field equations presented, November 1915',
  'sci-insulin-isolated': 'Banting and Best, summer 1921',
  'sci-hubble-finds-the-universe-expanding': 'Hubble\'s paper, 1929',
  'sci-living-coelacanth-found': 'Caught off East London, South Africa, December 1938',
  'sci-nuclear-fission-discovered': 'Hahn and Strassmann, December 1938',
  'sci-dna-double-helix': 'Watson and Crick in Nature, 25 April 1953',
  'sci-smallpox-declared-eradicated': 'World Health Assembly, 8 May 1980',
  'sci-ozone-hole-discovered': 'Farman, Gardiner and Shanklin in Nature, May 1985',
  'sci-human-genome-sequenced': 'Project declared complete, April 2003',
  'sci-crispr-gene-editing': 'Jinek, Charpentier and Doudna in Science, June 2012',
  'sci-first-image-of-a-black-hole': 'Event Horizon Telescope image released, 10 April 2019',
  'his-genghis-khan-proclaimed': 'Kurultai on the Onon River, 1206',
  'his-black-death-reaches-sicily': 'Genoese galleys at Messina, October 1347',
  'his-vasco-da-gama-reaches-india': 'Arrival at Calicut, 20 May 1498',
  'his-mayflower-lands-in-america': 'Arrival at Cape Cod, November 1620',
  'his-nelson-mandela-released': '11 February 1990',
  'fra-charlemagne-crowned-emperor': 'Rome, 25 December 800',
  'fra-hugh-capet-crowned-king': 'Coronation, July 987',
  'fra-joan-of-arc-lifts-the-siege-of-orleans': '8 May 1429',
  'fra-louis-xiv-moves-the-court-to-versailles': '6 May 1682',
  'fra-first-hot-air-balloon-flight': 'Annonay demonstration, 4 June 1783',
  'fra-slavery-abolished-for-good-in-france': 'Decree of 27 April 1848',
  'fra-women-vote-for-the-first-time': 'Municipal elections, 29 April 1945',
  'fra-death-penalty-abolished': 'Law of 9 October 1981',
  'fra-euro-coins-and-notes-arrive': '1 January 2002',
  'pop-first-crossword-puzzle': 'Arthur Wynne in the New York World, 21 December 1913',
  'pop-lego-brick-patented': 'Patent filed, 28 January 1958',
  'pop-pokemon-red-and-green': 'Japanese release, 27 February 1996',
  'pop-spotify-launched': 'Public launch, October 2008',
  'pop-minecraft-s-first-public-version': 'First public build, May 2009',
  'fli-first-parachute-jump-from-a-balloon': 'Garnerin over Paris, 22 October 1797',
  'fli-cayley-s-glider-carries-a-man': 'Brompton Dale, 1853',
  'fli-lilienthal-s-first-glider-flights': '1891',
  'fli-bleriot-flies-across-the-channel': '25 July 1909',
  'fli-first-liquid-fuelled-rocket': 'Auburn, Massachusetts, 16 March 1926',
  'fli-amelia-earhart-s-solo-atlantic-flight': '20–21 May 1932',
  'fli-sound-barrier-broken': 'Chuck Yeager in the Bell X-1, 14 October 1947',
  'fli-viking-1-lands-on-mars': '20 July 1976',
  'fli-first-iss-module-launched': 'Zarya launched, 20 November 1998',
  'fli-balloon-flies-nonstop-around-the-world': 'Landing in Egypt, 21 March 1999',
  'fli-new-horizons-flies-past-pluto': 'Closest approach, 14 July 2015',
};
