import {legalActions,playerView} from './rules.js';
const RULES={
  backhand:'BACKHAND: Two players, nine prize rounds. Each owns bid values 1–5. Both secretly choose one card; higher bid wins the current prize plus any tied carry. Ties carry the pot; a final tied pot is discarded. After every reveal the PLAYED CARDS ARE EXCHANGED into the opposite hands. No bid card is destroyed. Current and next prize are public, later order unknown. Maximize final score; account for giving your strong bid to your opponent and preserving flexibility. Use revealed bids and known exchanges, without inventing the hidden current bid.',
  closing:'CLOSING TIME: Two players, nine auction lots worth 1–3, three open at a time. Each owns five reusable cubes total. On your turn first place one reserve cube, move one own cube between lots, or skip. Then tick an auction clock; you cannot tick the lot you just invested in unless only one lot is open. A clock closes at three: majority wins the lot, equal positive counts favor its first bidder, and no cubes means no winner. Its cubes return to reserve and a new hidden lot opens. Both phases are actions in the supplied candidates. Maximize final score. Consider whether you can close a winning lot now, defend valuable lots, or create two threats. Spending all cubes on a low-value lot can lose better opportunities.',
  heist:'POCKET HEIST: Two players, five rounds. Each starts with three real alarms and three bluffs. Every round each has public outside and vault loot (vault is the higher value). Secretly choose a defense from your hand. Then secretly choose safe or raid against the OTHER player. Safe takes their outside loot and leaves their vault to them. Raid against a bluff takes both piles; raid against an alarm gives both piles to the defender. Both attacks resolve simultaneously. Each played defense is revealed, spent, and added to public used history. Unplayed hands and current guards remain hidden. Maximize final coin margin, not just your own gross reward. Public unspentAlarm counts include the current concealed guard; zero means that guard MUST be a bluff. Track remaining alarm/bluff counts and public behavior; value defending your own loot separately from attacking theirs. Bluff timing and scarce alarms matter.'
};
export function describeTurn(state,seat,previous=[]) {
  const observation=playerView(state,seat);
  const publicPlayers=observation.scores.map((score,p)=>({seat:p,you:p===seat,score,...(state.type==='heist'?{unspentAlarms:3-observation.used[p].filter(x=>x==='alarm').length,unspentBluffs:3-observation.used[p].filter(x=>x==='bluff').length}:{})}));
  return {game:'midnight-'+state.type,rules:RULES[state.type],observation:{...observation,you:seat,publicPlayers,ownPreviousActions:previous.slice(-6)},
    candidates:legalActions(observation,seat).map(action=>{
      const info={action,...(action.card?{card:observation.hands[seat].find(c=>c.id===action.card)}:{})};
      if(action.kind==='tick'){const lot=observation.auctions.find(l=>l?.id===action.lot);const winner=lot.cubes[0]===lot.cubes[1]?(lot.cubes[0]?lot.first:null):Number(lot.cubes[1]>lot.cubes[0]);info.publicOutcome={closesNow:lot.clock===2,winningSeat:winner,youWin:winner===seat,points:lot.value,yourCubes:lot.cubes[seat],opponentCubes:lot.cubes[1-seat]};}
      return info;
    })};
}
