import {loadAI,saveAI,forgetKeys} from './config.js';
import {PROVIDERS,listModels} from './client.js';
import {usageSnapshot,formatSpend} from './usage.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function openAISettings(onSave=()=>{}) {
  let draft=structuredClone(loadAI()),controller=new AbortController(),catalog=[];
  const dialog=document.createElement('dialog');dialog.className='arcade-ai-dialog';dialog.setAttribute('aria-label','Shared AI settings');
  const style=document.createElement('style');style.textContent=`.arcade-ai-dialog{background:#172c28;color:#fff5da;border:1px solid #b5a46b;border-radius:14px;padding:24px;width:min(520px,94vw);max-height:90vh;font:15px/1.5 system-ui;box-sizing:border-box}.arcade-ai-dialog::backdrop{background:#071411dc}.arcade-ai-dialog h2{margin:0 0 12px}.arcade-ai-dialog label{display:block;margin:14px 0 5px}.arcade-ai-dialog input:not([type=checkbox]),.arcade-ai-dialog select{display:block;box-sizing:border-box;width:100%;padding:10px;color:inherit;background:#0a1e1a;border:1px solid #6d8472;border-radius:5px;font:inherit}.arcade-ai-dialog button{padding:10px;margin:12px 8px 0 0;border:0;border-radius:5px;background:#eed08c;color:#11221d;cursor:pointer;font:inherit}.arcade-ai-dialog small{display:block;color:#bdcbbf}.arcade-ai-dialog a{color:#eed08c}.arcade-ai-dialog .ai-error{color:#ffb8aa}.arcade-ai-dialog .ai-check{display:flex;gap:10px;align-items:center}`;
  document.head.append(style);document.body.append(dialog);
  function capture(){const p=draft.provider;draft.keys[p]=dialog.querySelector('#shared-key').value.trim();draft.models[p]=dialog.querySelector('#shared-model').value.trim();draft.efforts[p]=dialog.querySelector('#shared-effort').value;draft.tokenBudget=Number(dialog.querySelector('#shared-budget').value);draft.rememberKeys=dialog.querySelector('#shared-remember').checked;}
  function render(){const p=draft.provider,info=PROVIDERS[p],spend=usageSnapshot().total;
    dialog.innerHTML=`<h2>AI settings</h2><small>Shared with Similo and all card games on this site. Calls use your account.</small><label for="shared-provider">Provider</label><select id="shared-provider">${Object.entries(PROVIDERS).map(([id,v])=>`<option value="${id}" ${id===p?'selected':''}>${v.name}</option>`).join('')}</select><label for="shared-key">API key · <a href="${info.keyUrl}" target="_blank" rel="noreferrer">Get a key</a></label><input type="password" id="shared-key" autocomplete="off" value="${esc(draft.keys[p]||'')}"><label class="ai-check"><input type="checkbox" id="shared-remember" ${draft.rememberKeys?'checked':''}>Remember keys on this device</label><small>Keys stay out of invites, game saves and opponent messages. Unchecked keys stay only in this tab until you close or reload it.</small><label for="shared-model">Model</label><input id="shared-model" list="shared-models" value="${esc(draft.models[p])}"><datalist id="shared-models">${catalog.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</datalist><button data-ai="models">Load available models</button><label for="shared-effort">Reasoning effort</label><select id="shared-effort">${info.efforts.map(e=>`<option ${draft.efforts[p]===e?'selected':''}>${e}</option>`).join('')}</select><small>Use an effort supported by the selected model. Provider errors are shown for unsupported combinations.</small><label for="shared-budget">Output token budget</label><input type="number" id="shared-budget" min="2048" max="32768" step="1024" value="${draft.tokenBudget}"><p>All card-game API spending: <strong>${esc(formatSpend(spend))}</strong> · ${spend.requests} requests</p><p class="ai-error" role="alert"></p><button data-ai="save">Save settings</button><button data-ai="close">Cancel</button><button data-ai="forget">Forget saved keys</button>`;
    dialog.querySelector('#shared-provider').onchange=e=>{capture();draft.provider=e.target.value;catalog=[];render();};
  }
  dialog.onclick=async e=>{const action=e.target.dataset.ai;if(!action)return;
    if(action==='close'){dialog.close();return;}capture();
    if(action==='save'){if(!draft.models[draft.provider]){dialog.querySelector('.ai-error').textContent='Enter a model name.';return;}const saved=saveAI(draft);onSave();if(!saved){dialog.querySelector('.ai-error').textContent='Settings are active in this tab, but browser storage is unavailable.';return;}dialog.close();}
    if(action==='forget'){forgetKeys();draft=loadAI();render();onSave();}
    if(action==='models'){e.target.disabled=true;const p=draft.provider;try{const found=await listModels(p,draft.keys[p],AbortSignal.any([controller.signal,AbortSignal.timeout(30000)]),false);if(draft.provider!==p)return;catalog=found;render();}catch(error){if(!dialog.open)return;dialog.querySelector('.ai-error').textContent=error.message;e.target.disabled=false;}}
  };
  dialog.addEventListener('close',()=>{controller.abort();dialog.remove();style.remove();});render();dialog.showModal();
}
export function aiStatusHtml({busy=false,error='',controller=false}={}) {
  if(!busy&&!error)return '';
  return `<div class="disconnect" role="${error?'alert':'status'}"><span>${error?esc(error):'AI is choosing a move…'}</span>${controller?`<button class="button compact gold" data-action="${error?'retry-ai':'cancel-ai'}">${error?'RETRY':'PAUSE'}</button><button class="button compact outline" data-action="ai-settings">AI SETTINGS</button>`:''}</div>`;
}
