// Run after npm run build:assets and npm run dev.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--enable-unsafe-swiftshader',...(process.env.CHROMIUM_NO_SANDBOX==='1'?['--no-sandbox']:[])]});const c=await browser.newContext({viewport:{width:1280,height:900}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);
async function frame(){return(await p.locator('#game-frame').elementHandle()).contentFrame();}
try{
 await p.goto((process.env.GAMES_URL||'http://127.0.0.1:8787')+'/together/?game=nonocube');let f=await frame();await f.getByRole('button',{name:'Skip',exact:true}).click();await f.getByRole('button',{name:'Play',exact:true}).click();await f.locator('.coll-card').first().click();await f.locator('.gallery').getByRole('button',{name:'Play',exact:true}).click();await f.locator('.play').waitFor();await f.waitForFunction(()=>window.__gameCheckpoint?.capture()?.id);const before=await f.evaluate(()=>{window.__gameCheckpoint.save();return window.__gameCheckpoint.capture();});await p.reload();f=await frame();await f.locator('.play').waitFor();const after=await f.evaluate(()=>window.__gameCheckpoint.capture());assert.equal(after.id,before.id);assert.equal(after.progress.state,before.progress.state);console.log('Nonocube restored',after.id);
 await p.goto((process.env.GAMES_URL||'http://127.0.0.1:8787')+'/together/?game=pawn-quest');f=await frame();await f.waitForFunction(()=>window.pawnQuest);await f.evaluate(()=>window.pawnQuest.nav.arena());await f.locator('.bot-card').filter({hasText:'Two players'}).click();await f.getByRole('button',{name:'Start game ▶',exact:true}).click();await f.waitForFunction(()=>window.__board?.pos);await f.evaluate(()=>{const board=window.__board;board.onMove([board.pos.moveFromUci('e2e4')]);});await f.waitForFunction(()=>window.pawnQuest.active.capture()?.arena.moves.length===1);const fen=await f.evaluate(()=>{window.__gameCheckpoint.save();return window.__board.pos.toFEN();});await p.reload();f=await frame();await f.waitForFunction(()=>window.__board?.pos);assert.equal(await f.evaluate(()=>window.__board.pos.toFEN()),fen);console.log('Pawn arena restored',fen);
 // Without a room, solo saves are listed in Play together and resume from there.
 await p.goto((process.env.GAMES_URL||'http://127.0.0.1:8787')+'/');await p.locator('#show-friend-panel').click();await p.locator('#start-saves summary').click();
 await p.locator('#start-saves-list button').filter({hasText:'Nonocube'}).click();f=await frame();await f.locator('.play').waitFor();
 assert.equal((await f.evaluate(()=>window.__gameCheckpoint.capture())).id,after.id);console.log('Saved game resumed from the panel');assert.deepEqual(errors,[]);
}finally{await browser.close();}
